import { CommonModule } from '@angular/common';
import { Component, HostListener, OnDestroy, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { ConfirmacionService } from '../../../core/services/confirmacion.service';
import { GaleriaPublicacion, PortalAcademicoService, Publicacion } from '../../../core/services/portal-academico.service';

@Component({ selector: 'app-portal-detail', standalone: true, imports: [CommonModule, FormsModule, RouterLink], templateUrl: './portal-detail.component.html', styleUrls: ['./portal-detail.component.scss'] })
export class PortalDetailComponent implements OnInit, OnDestroy {
  private readonly dialogos=inject(ConfirmacionService); private readonly route=inject(ActivatedRoute); private readonly portal=inject(PortalAcademicoService); private readonly auth=inject(AuthService);
  publicacion?:Publicacion; imagen?:string; relacionadas:Publicacion[]=[]; imagenesRelacionadas=new Map<string,string>(); cargando=true; editando=false; titulo=''; contenido=''; archivo?:File; mensaje=''; error=''; guardando=false; indiceLightbox=-1;
  get puedeGestionar(){const p=this.publicacion,u=this.auth.user;return !!p&&!!u&&(u.rol==='ADMINISTRADOR'||(u.rol==='DOCENTE'&&p.autor?.id===u.id));} get galeria():GaleriaPublicacion[]{return this.publicacion?.galeria?.slice().sort((a,b)=>a.orden-b.orden)??[];} get itemLightbox(){return this.indiceLightbox<0?undefined:this.galeria[this.indiceLightbox];}
  ngOnInit(){this.route.paramMap.subscribe(params=>{const id=params.get('id');if(id)this.cargar(id);});}
  ngOnDestroy(){if(this.imagen?.startsWith('blob:'))URL.revokeObjectURL(this.imagen);this.imagenesRelacionadas.forEach(url=>{if(url.startsWith('blob:'))URL.revokeObjectURL(url);});}
  @HostListener('document:keydown.escape') cerrarLightbox(){this.indiceLightbox=-1;} @HostListener('document:keydown.arrowright') siguiente(){if(this.indiceLightbox>=0)this.indiceLightbox=(this.indiceLightbox+1)%this.galeria.length;} @HostListener('document:keydown.arrowleft') anterior(){if(this.indiceLightbox>=0)this.indiceLightbox=(this.indiceLightbox-1+this.galeria.length)%this.galeria.length;}
  cargar(id:string){this.cargando=true;this.error='';this.mensaje='';this.editando=false;this.relacionadas=[];this.imagenesRelacionadas.forEach(url=>{if(url.startsWith('blob:'))URL.revokeObjectURL(url);});this.imagenesRelacionadas.clear();this.indiceLightbox=-1;this.portal.obtener(id).subscribe({next:p=>{if(this.imagen?.startsWith('blob:'))URL.revokeObjectURL(this.imagen);this.publicacion=p;this.titulo=p.titulo;this.contenido=p.contenido;this.imagen=this.galeria[0]?.imagen;this.cargando=false;this.cargarImagen(p);this.cargarRelacionadas(p.id);window.scrollTo({top:0,behavior:'auto'});},error:e=>{this.cargando=false;this.error=e.error?.message??'No fue posible cargar la publicación.';}});}
  editar(){if(!this.publicacion)return;this.editando=true;this.titulo=this.publicacion.titulo;this.contenido=this.publicacion.contenido;this.mensaje='';this.error='';}
  guardar(){if(!this.publicacion||!this.titulo.trim()||!this.contenido.trim()){this.error='Título y contenido son obligatorios.';return;}this.guardando=true;this.portal.actualizar(this.publicacion.id,{titulo:this.titulo.trim(),contenido:this.contenido.trim()}).subscribe({next:p=>{this.publicacion=p;this.editando=false;this.guardando=false;this.mensaje='Cambios guardados.';this.cargarImagen(p,true);},error:e=>{this.guardando=false;this.error=e.error?.message??'No fue posible actualizar la publicación.';}});}
  cambiarEstado(accion:'publicar'|'ocultar'|'archivar'){if(!this.publicacion)return;void this.dialogos.solicitar('Confirmar cambio de estado','¿Deseas ' + accion + ' esta publicación?',accion==='publicar'?'Publicar':'Confirmar').then(ok=>{if(!ok||!this.publicacion)return;this.portal[accion](this.publicacion.id).subscribe({next:p=>{this.publicacion=p;this.mensaje=`Publicación ${accion==='publicar'?'publicada':accion==='ocultar'?'ocultada':'archivada'}.`;},error:e=>this.error=e.error?.message??'No fue posible cambiar el estado.'});});}
  seleccionarArchivo(e:Event){const a=(e.target as HTMLInputElement).files?.[0];if(!a)return;if(!['image/jpeg','image/png','image/webp'].includes(a.type)||a.size>5*1024*1024){this.error='La imagen debe ser JPG, PNG o WEBP y pesar como máximo 5 MB.';return;}this.archivo=a;this.error='';}
  subirImagen(){if(!this.publicacion||!this.archivo)return;this.guardando=true;this.portal.subirImagen(this.publicacion.id,this.archivo).subscribe({next:p=>{this.publicacion=p;this.archivo=undefined;this.guardando=false;this.mensaje='Imagen actualizada.';this.cargarImagen(p,true);},error:e=>{this.guardando=false;this.error=e.error?.message??'No fue posible cargar la imagen.';}});}
  eliminarImagen(){if(!this.publicacion)return;void this.dialogos.solicitar('Eliminar imagen','Esta acción retirará la imagen de la publicación.','Eliminar').then(ok=>{if(!ok||!this.publicacion)return;this.portal.eliminarImagen(this.publicacion.id).subscribe({next:()=>{this.imagen=undefined;this.publicacion={...this.publicacion!,tieneImagen:false};this.mensaje='Imagen eliminada.';},error:e=>this.error=e.error?.message??'No fue posible eliminar la imagen.'});});}
  resumen(p:Publicacion){const t=(p.resumen||p.contenido.replace(/<[^>]+>/g,' ')).trim().replace(/\s+/g,' ');return t.length>112?`${t.slice(0,t.lastIndexOf(' ',112)).trim()}…`:t;} imagenRelacionada(id:string){return this.imagenesRelacionadas.get(id);}
  abrirLightbox(i:number){this.indiceLightbox=i;}
  private cargarImagen(p:Publicacion,reemplazar=false){if(!p.tieneImagen)return;if(this.imagen&&!reemplazar)return;this.portal.imagen(p.id).subscribe({next:b=>{if(this.imagen?.startsWith('blob:'))URL.revokeObjectURL(this.imagen);this.imagen=URL.createObjectURL(b);}});}
  private cargarRelacionadas(id:string){this.portal.listar().subscribe({next:ps=>{this.relacionadas=ps.filter(p=>p.id!==id&&p.estado==='PUBLICADA').slice(0,3);this.relacionadas.forEach(p=>{if(p.tieneImagen)this.portal.imagen(p.id).subscribe({next:b=>this.imagenesRelacionadas.set(p.id,URL.createObjectURL(b))});else if(p.galeria?.length)this.imagenesRelacionadas.set(p.id,p.galeria.slice().sort((a,b)=>a.orden-b.orden)[0].imagen);});}});}
}