-- Fase 2: Orden Operacional para la versión de defensa.
-- Ejecutado manualmente; TypeORM mantiene synchronize=false y migrationsRun=false.
BEGIN;

CREATE TABLE public.maquinaria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  factor_consumo_hilo NUMERIC(10,4) NOT NULL,
  estado public.estado_catalogo NOT NULL DEFAULT 'ACTIVO',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_maquinaria_codigo CHECK (btrim(codigo) <> ''),
  CONSTRAINT ck_maquinaria_nombre CHECK (btrim(nombre) <> ''),
  CONSTRAINT ck_maquinaria_factor CHECK (factor_consumo_hilo >= 0)
);

CREATE UNIQUE INDEX uq_maquinaria_codigo_ci ON public.maquinaria (lower(codigo));
CREATE UNIQUE INDEX uq_maquinaria_nombre_ci ON public.maquinaria (lower(nombre));

CREATE TABLE public.orden_operacional (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_costeo_id BIGINT NOT NULL UNIQUE REFERENCES public.version_costeo(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  total_segundos NUMERIC(14,4) NOT NULL DEFAULT 0,
  total_costura_cm NUMERIC(14,4) NOT NULL DEFAULT 0,
  total_hilo_cm NUMERIC(14,4) NOT NULL DEFAULT 0,
  total_hilo_metros NUMERIC(14,4) NOT NULL DEFAULT 0,
  tiempo_real_minutos NUMERIC(14,4) NOT NULL DEFAULT 0,
  tiempo_estandar_minutos NUMERIC(14,4) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_orden_operacional_totales CHECK (total_segundos >= 0 AND total_costura_cm >= 0 AND total_hilo_cm >= 0 AND total_hilo_metros >= 0 AND tiempo_real_minutos >= 0 AND tiempo_estandar_minutos >= 0)
);

CREATE TABLE public.orden_operacional_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_operacional_id BIGINT NOT NULL REFERENCES public.orden_operacional(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  orden_visualizacion INTEGER NOT NULL,
  operacion VARCHAR(200) NOT NULL,
  descripcion TEXT NULL,
  maquinaria_id BIGINT NOT NULL REFERENCES public.maquinaria(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  maquinaria_nombre_aplicada VARCHAR(100) NOT NULL,
  factor_hilo_aplicado NUMERIC(10,4) NOT NULL,
  tiempo_segundos NUMERIC(14,4) NOT NULL,
  costura_cm NUMERIC(14,4) NOT NULL DEFAULT 0,
  cantidad_hilo_cm NUMERIC(14,4) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_ood_orden CHECK (orden_visualizacion > 0),
  CONSTRAINT ck_ood_operacion CHECK (btrim(operacion) <> ''),
  CONSTRAINT ck_ood_factor CHECK (factor_hilo_aplicado >= 0),
  CONSTRAINT ck_ood_tiempo CHECK (tiempo_segundos > 0),
  CONSTRAINT ck_ood_costura CHECK (costura_cm >= 0),
  CONSTRAINT ck_ood_hilo CHECK (cantidad_hilo_cm >= 0),
  CONSTRAINT uq_ood_orden_posicion UNIQUE (orden_operacional_id, orden_visualizacion)
);

CREATE INDEX idx_ood_maquinaria ON public.orden_operacional_detalle (maquinaria_id);

INSERT INTO public.maquinaria (codigo, nombre, factor_consumo_hilo, estado) VALUES
  ('MAQ-001', 'Recta', 3.00, 'ACTIVO'),
  ('MAQ-002', 'Overlock', 15.87, 'ACTIVO'),
  ('MAQ-003', 'Recubridora', 3.41, 'ACTIVO'),
  ('MAQ-004', 'Manual', 0.00, 'ACTIVO'),
  ('MAQ-005', 'Fusionadora', 0.00, 'ACTIVO'),
  ('MAQ-006', 'Ojal recto', 45.00, 'ACTIVO'),
  ('MAQ-007', 'Botonadora', 9.00, 'ACTIVO');

COMMIT;
