-- Fase 3: Cuadros 1–6 de la Ficha de Costos.
-- DDL manual controlado; TypeORM conserva synchronize=false y migrationsRun=false.
BEGIN;

CREATE TABLE public.version_costeo_calculo_base (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_costeo_id BIGINT NOT NULL UNIQUE REFERENCES public.version_costeo(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  sbu NUMERIC(12,2) NULL,
  numero_operarias INTEGER NOT NULL DEFAULT 1,
  semanas_mes INTEGER NOT NULL DEFAULT 4,
  dias_semana INTEGER NOT NULL DEFAULT 5,
  minutos_dia INTEGER NOT NULL DEFAULT 480,
  eficiencia NUMERIC(6,4) NOT NULL DEFAULT 0.8000,
  iess_patronal NUMERIC(14,6) NOT NULL DEFAULT 0,
  decimo_tercero NUMERIC(14,6) NOT NULL DEFAULT 0,
  decimo_cuarto NUMERIC(14,6) NOT NULL DEFAULT 0,
  fondos_reserva NUMERIC(14,6) NOT NULL DEFAULT 0,
  vacaciones NUMERIC(14,6) NOT NULL DEFAULT 0,
  total_salario_mensual NUMERIC(14,6) NOT NULL DEFAULT 0,
  costo_mensual_mod NUMERIC(14,6) NOT NULL DEFAULT 0,
  minutos_productivos_mes NUMERIC(14,6) NOT NULL DEFAULT 0,
  costo_minuto_mod NUMERIC(14,6) NOT NULL DEFAULT 0,
  sueldo_personal_administrativo NUMERIC(14,6) NOT NULL DEFAULT 0,
  varios_moi NUMERIC(14,6) NOT NULL DEFAULT 0,
  total_moi NUMERIC(14,6) NOT NULL DEFAULT 0,
  costo_minuto_moi NUMERIC(14,6) NOT NULL DEFAULT 0,
  gastos_generales NUMERIC(14,6) NOT NULL DEFAULT 0,
  arriendo NUMERIC(14,6) NOT NULL DEFAULT 0,
  papeleria NUMERIC(14,6) NOT NULL DEFAULT 0,
  higiene NUMERIC(14,6) NOT NULL DEFAULT 0,
  cafeteria NUMERIC(14,6) NOT NULL DEFAULT 0,
  total_gastos_generales NUMERIC(14,6) NOT NULL DEFAULT 0,
  costo_minuto_gastos_generales NUMERIC(14,6) NOT NULL DEFAULT 0,
  total_horas_patronaje_corte NUMERIC(14,4) NOT NULL DEFAULT 0,
  total_costo_patronaje_corte NUMERIC(14,6) NOT NULL DEFAULT 0,
  costo_minuto_patronaje_corte NUMERIC(14,6) NOT NULL DEFAULT 0,
  total_horas_diseno NUMERIC(14,4) NOT NULL DEFAULT 0,
  total_costo_diseno NUMERIC(14,6) NOT NULL DEFAULT 0,
  costo_minuto_diseno NUMERIC(14,6) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_vccb_sbu CHECK (sbu IS NULL OR sbu > 0),
  CONSTRAINT ck_vccb_operarias CHECK (numero_operarias > 0),
  CONSTRAINT ck_vccb_parametros CHECK (semanas_mes > 0 AND dias_semana > 0 AND minutos_dia > 0 AND eficiencia > 0 AND eficiencia <= 1),
  CONSTRAINT ck_vccb_no_negativos CHECK (
    sueldo_personal_administrativo >= 0 AND varios_moi >= 0 AND gastos_generales >= 0 AND arriendo >= 0 AND
    papeleria >= 0 AND higiene >= 0 AND cafeteria >= 0 AND total_salario_mensual >= 0 AND costo_mensual_mod >= 0 AND
    minutos_productivos_mes >= 0 AND costo_minuto_mod >= 0 AND total_moi >= 0 AND costo_minuto_moi >= 0 AND
    total_gastos_generales >= 0 AND costo_minuto_gastos_generales >= 0 AND total_horas_patronaje_corte >= 0 AND
    total_costo_patronaje_corte >= 0 AND costo_minuto_patronaje_corte >= 0 AND total_horas_diseno >= 0 AND
    total_costo_diseno >= 0 AND costo_minuto_diseno >= 0
  )
);

CREATE TABLE public.version_costeo_calculo_actividad (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_costeo_calculo_base_id BIGINT NOT NULL REFERENCES public.version_costeo_calculo_base(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  grupo VARCHAR(30) NOT NULL,
  codigo VARCHAR(40) NOT NULL,
  actividad VARCHAR(150) NOT NULL,
  orden_visualizacion INTEGER NOT NULL,
  horas NUMERIC(12,4) NOT NULL DEFAULT 0,
  tarifa_hora_aplicada NUMERIC(12,2) NOT NULL,
  costo NUMERIC(14,6) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_vcca_grupo CHECK (grupo IN ('PATRONAJE_CORTE', 'DISENO')),
  CONSTRAINT ck_vcca_codigo CHECK (btrim(codigo) <> ''),
  CONSTRAINT ck_vcca_actividad CHECK (btrim(actividad) <> ''),
  CONSTRAINT ck_vcca_orden CHECK (orden_visualizacion > 0),
  CONSTRAINT ck_vcca_horas CHECK (horas >= 0),
  CONSTRAINT ck_vcca_tarifa CHECK (tarifa_hora_aplicada > 0),
  CONSTRAINT ck_vcca_costo CHECK (costo >= 0),
  CONSTRAINT uq_vcca_version_codigo UNIQUE (version_costeo_calculo_base_id, codigo),
  CONSTRAINT uq_vcca_version_orden UNIQUE (version_costeo_calculo_base_id, orden_visualizacion)
);

CREATE INDEX idx_vcca_base_grupo ON public.version_costeo_calculo_actividad (version_costeo_calculo_base_id, grupo, orden_visualizacion);

COMMIT;
