import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { forkJoin, Observable } from 'rxjs';
import { AuthService } from '../../../core/services/auth.service';
import { ConfirmacionService } from '../../../core/services/confirmacion.service';
import { CatalogosService, Insumo, Tela, TipoPrenda } from '../../../core/services/catalogos.service';
import { ProduccionService } from '../../../core/services/produccion.service';
import { PresentacionNumeroPipe } from '../../../shared/pipes/presentacion-numero.pipe';
import { CosteoService, DetalleVersionCosteo, MedidaConfiguracion, VersionCosteoInsumo, VersionCosteoMedida, VersionCosteoTela, Maquinaria, OrdenOperacionalDetalle, OrdenOperacionalResumen, CalculosBaseVersion } from '../../../core/services/costeo.service';

type FilaMedida = MedidaConfiguracion & { valor: number | null };
type ModalAccion = 'finalizar' | 'cancelar' | 'nueva' | null;
@Component({ selector: 'app-costeo-detail', standalone: true, imports: [CommonModule, FormsModule, RouterLink, PresentacionNumeroPipe], templateUrl: './costeo-detail.component.html', styleUrl: './costeo-detail.component.scss' })
export class CosteoDetailComponent implements OnInit {
  private readonly dialogos = inject(ConfirmacionService); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private readonly costeo = inject(CosteoService); private readonly produccion = inject(ProduccionService); private readonly catalogos = inject(CatalogosService); private readonly auth = inject(AuthService);
  id = ''; version?: DetalleVersionCosteo; medidas: FilaMedida[] = []; telas: VersionCosteoTela[] = []; insumos: VersionCosteoInsumo[] = []; detallesOperacionales: OrdenOperacionalDetalle[] = []; resumenOperacional?: OrdenOperacionalResumen; catalogoTelas: Tela[] = []; catalogoInsumos: Insumo[] = []; maquinarias: Maquinaria[] = []; tiposPrenda: TipoPrenda[] = []; tipoPrendaId = ''; calculosBase?: CalculosBaseVersion;
  mensaje = ''; cargando = false; ordenProduccionId?: string; sinOrdenProduccion = false; modal: ModalAccion = null; nombre = ''; descripcion = ''; manoObra = 0; ganancia = 0;
  nuevaTelaId = ''; nuevaTelaCantidad: number | null = null; nuevaTelaPrecio: number | null = null; nuevaTelaObservacion = ''; mostrarNuevaTela=false; nuevaTelaNombre=''; nuevaTelaAncho:number|null=null; nuevaTelaCatalogoPrecio:number|null=null; nuevoInsumoId = ''; nuevoInsumoCantidad: number | null = null; nuevoInsumoPrecio: number | null = null; nuevoInsumoObservacion = ''; mostrarNuevoInsumo=false; nuevoInsumoNombre=''; nuevoInsumoUnidad=''; nuevoInsumoCatalogoPrecio:number|null=null; nuevaOperacion = ''; nuevaMaquinariaId = ''; nuevoTiempoSegundos: number | null = null; nuevaCosturaCm: number | null = null; nuevaDescripcionOperacion = '';
  editandoTela?: VersionCosteoTela; editandoInsumo?: VersionCosteoInsumo; editandoOperacion?: OrdenOperacionalDetalle; editCantidad: number | null = null; editPrecio: number | null = null; editObservacion = '';
  get estudiante(): boolean { return this.auth.user?.rol === 'ESTUDIANTE'; }
  get editable(): boolean { return this.estudiante && this.version?.estado === 'BORRADOR'; }
  ngOnInit(): void { this.route.queryParamMap.subscribe(q => { if (q.get('created') === '1') this.mensaje = 'Proyecto creado correctamente. Complete la primera versión de costeo.'; }); this.route.paramMap.subscribe(params => { this.id = params.get('id') ?? ''; this.cargarCatalogos(); this.refrescar(); }); }
  refrescar(): void { if (!this.id) return; this.cargando = true; forkJoin({ version: this.costeo.obtenerVersion(this.id), configuracion: this.costeo.configuracionMedidas(this.id), guardadas: this.costeo.obtenerMedidas(this.id), telas: this.costeo.obtenerTelas(this.id), insumos: this.costeo.obtenerInsumos(this.id), operacional: this.costeo.obtenerOrdenOperacional(this.id), calculosBase: this.costeo.obtenerCalculosBase(this.id) }).subscribe({ next: data => { this.version = data.version; this.nombre = data.version.nombre; this.tipoPrendaId = data.version.tipoPrendaId ?? ''; this.descripcion = data.version.descripcion ?? ''; this.manoObra = Number(data.version.porcentajeManoObra); this.ganancia = Number(data.version.porcentajeGanancia); const valores = new Map(data.guardadas.map(m => [String(m.tipo_prenda_medida_id), Number(m.valor)])); this.medidas = data.configuracion.map(c => ({ ...c, valor: valores.get(String(c.tipo_prenda_medida_id)) ?? null })); this.telas = data.telas; this.insumos = data.insumos; this.detallesOperacionales = data.operacional.detalles; this.resumenOperacional = data.operacional.orden; this.calculosBase = data.calculosBase; this.verificarProduccion(data.version); this.cargando = false; }, error: e => { this.cargando = false; this.mensaje = this.error(e); } }); }
  verificarProduccion(version: DetalleVersionCosteo): void { if (version.estado !== 'FINALIZADA') return; this.produccion.ordenPorVersion(version.id).subscribe({ next: orden => { this.ordenProduccionId = orden.id; this.sinOrdenProduccion = false; }, error: () => { this.ordenProduccionId = undefined; this.sinOrdenProduccion = true; } }); }
  crearOrdenProduccion(): void { if (!this.version) return; void this.dialogos.solicitar('Crear orden de producción','Se creará la orden para esta versión finalizada.','Crear orden').then(ok=>{if(!ok||!this.version)return;this.cargando = true; this.produccion.crearOrden(this.version.id).subscribe({ next: orden => void this.router.navigate(['/produccion', orden.id]), error: e => { this.cargando = false; this.mensaje = this.error(e); } });}); }
  verProduccion(): void { if (this.ordenProduccionId) void this.router.navigate(['/produccion', this.ordenProduccionId]); }
  cargarCatalogos(): void { this.catalogos.listar<TipoPrenda>('tipos-prenda', { estado: 'ACTIVO' }).subscribe({ next: x => this.tiposPrenda = [...x].sort((a,b)=>a.nombre.localeCompare(b.nombre,'es',{sensitivity:'base'})) }); this.catalogos.listar<Tela>('telas', { estado: 'ACTIVO' }).subscribe({ next: x => this.catalogoTelas = [...x].sort((a,b)=>a.nombre.localeCompare(b.nombre,'es',{sensitivity:'base'})) }); this.catalogos.listar<Insumo>('insumos', { estado: 'ACTIVO' }).subscribe({ next: x => this.catalogoInsumos = [...x].sort((a,b)=>a.nombre.localeCompare(b.nombre,'es',{sensitivity:'base'})) }); this.costeo.listarMaquinarias({ estado: 'ACTIVO' }).subscribe({ next: x => this.maquinarias = [...x].sort((a,b)=>a.nombre.localeCompare(b.nombre,'es',{sensitivity:'base'})), error: () => this.maquinarias = [] }); }
  guardarCabecera(): void { if (this.editable && this.nombre.trim()) this.ejecutar(this.costeo.actualizarVersion(this.id, { nombre: this.nombre.trim(), descripcion: this.descripcion.trim() || undefined }), 'Cabecera actualizada.'); }
  guardarPrenda(): void { if (!this.editable || !this.tipoPrendaId) { this.mensaje='Selecciona un tipo de prenda.'; return; } this.ejecutar(this.costeo.actualizarVersion(this.id, { tipoPrendaId: this.tipoPrendaId } as never), 'Tipo de prenda actualizado.'); }
    guardarPorcentajes(): void { if (!this.editable || !this.porcentajeValido(this.manoObra) || !this.porcentajeValido(this.ganancia)) { this.mensaje = 'Los porcentajes deben estar entre 0 y 100.'; return; } this.ejecutar(this.costeo.actualizarVersion(this.id, { porcentajeManoObra: this.manoObra, porcentajeGanancia: this.ganancia }), 'Porcentajes actualizados.'); }
  guardarCalculosBase(): void {
    const base = this.calculosBase;
    if (!this.editable || !base) return;
    if (base.sbu !== null && Number(base.sbu) <= 0) { this.mensaje = 'El SBU debe ser mayor que cero.'; return; }
    if (!Number.isInteger(Number(base.numeroOperarias)) || Number(base.numeroOperarias) < 1) { this.mensaje = 'El número de operarias debe ser un entero mayor que cero.'; return; }
    const actividades = [...base.patronajeCorte.actividades, ...base.diseno.actividades];
    if (actividades.some(item => Number(item.horas) < 0)) { this.mensaje = 'Las horas no pueden ser negativas.'; return; }
    this.ejecutar(this.costeo.actualizarCalculosBase(this.id, {
      ...(base.sbu === null ? {} : { sbu: Number(base.sbu) }), numeroOperarias: Number(base.numeroOperarias),
      sueldoPersonalAdministrativo: Number(base.moi.sueldoPersonalAdministrativo), variosMoi: Number(base.moi.variosMoi),
      gastosGenerales: Number(base.gastosGenerales.gastosGenerales), arriendo: Number(base.gastosGenerales.arriendo),
      papeleria: Number(base.gastosGenerales.papeleria), higiene: Number(base.gastosGenerales.higiene), cafeteria: Number(base.gastosGenerales.cafeteria),
      actividades: actividades.map(item => ({ codigo: item.codigo, horas: Number(item.horas) })),
    }), 'Cálculos base actualizados.');
  }
  guardarUtilidad(): void { const final = this.calculosBase?.costoFinal; if (!this.editable || !final) return; if (Number(final.porcentajeUtilidad) < 0) { this.mensaje='La utilidad no puede ser negativa.'; return; } this.ejecutar(this.costeo.actualizarUtilidad(this.id, Number(final.porcentajeUtilidad)), 'Costo final recalculado.'); }
  guardarMedidas(): void { const medidas = this.medidas.filter(m => m.valor !== null && Number(m.valor) > 0).map(m => ({ tipoPrendaMedidaId: Number(m.tipo_prenda_medida_id), valor: Number(m.valor) })); if (!this.editable || !medidas.length) { this.mensaje = 'Registra al menos una medida válida.'; return; } this.ejecutar(this.costeo.guardarMedidas(this.id, { medidas }), 'Medidas guardadas.'); }
  agregarTela(): void { if (!this.editable || !this.nuevaTelaId || !this.nuevaTelaCantidad || this.nuevaTelaCantidad <= 0) { this.mensaje = 'Selecciona una tela e indica una cantidad mayor que cero.'; return; } this.ejecutar(this.costeo.agregarTela(this.id, { telaId: Number(this.nuevaTelaId), cantidadMetros: this.nuevaTelaCantidad, cantidadMetrosSugerida: null, reglaConsumoTelaId: null, precioMetroAplicado: this.nuevaTelaPrecio || undefined, observacion: this.nuevaTelaObservacion.trim() || undefined }), 'Tela agregada.', () => { this.nuevaTelaId=''; this.nuevaTelaCantidad=null; this.nuevaTelaPrecio=null; this.nuevaTelaObservacion=''; }); }
  crearTelaCatalogo(): void { if(!this.editable||!this.nuevaTelaNombre.trim()||!this.nuevaTelaAncho||!this.nuevaTelaCatalogoPrecio){this.mensaje='Completa nombre, ancho y precio de la tela.';return;} this.ejecutar(this.costeo.crearTelaCatalogo(this.id,{nombre:this.nuevaTelaNombre.trim(),anchoCm:this.nuevaTelaAncho,precioMetro:this.nuevaTelaCatalogoPrecio}),'Tela creada en el catálogo.',()=>{this.mostrarNuevaTela=false;this.nuevaTelaNombre='';this.nuevaTelaAncho=null;this.nuevaTelaCatalogoPrecio=null;this.cargarCatalogos();}); }
  crearInsumoCatalogo(): void { if(!this.editable||!this.nuevoInsumoNombre.trim()||!this.nuevoInsumoUnidad.trim()||!this.nuevoInsumoCatalogoPrecio){this.mensaje='Completa nombre, unidad y precio del insumo.';return;} this.ejecutar(this.costeo.crearInsumoCatalogo(this.id,{nombre:this.nuevoInsumoNombre.trim(),unidadMedida:this.nuevoInsumoUnidad.trim(),precioUnitario:this.nuevoInsumoCatalogoPrecio}),'Insumo creado en el catálogo.',()=>{this.mostrarNuevoInsumo=false;this.nuevoInsumoNombre='';this.nuevoInsumoUnidad='';this.nuevoInsumoCatalogoPrecio=null;this.cargarCatalogos();}); }  abrirEdicionTela(x: VersionCosteoTela): void { this.editandoTela=x; this.editCantidad=Number(x.cantidad_metros); this.editPrecio=Number(x.precio_metro_aplicado); this.editObservacion=x.observacion ?? ''; }
  guardarTela(): void { if (this.editandoTela && this.editCantidad && this.editCantidad > 0) this.ejecutar(this.costeo.actualizarTela(this.id, this.editandoTela.id, { cantidadMetros:this.editCantidad, precioMetroAplicado:this.editPrecio || undefined, observacion:this.editObservacion.trim() || undefined }), 'Tela actualizada.', () => this.editandoTela=undefined); }
  eliminarTela(x: VersionCosteoTela): void { void this.dialogos.solicitar('Quitar tela','¿Deseas quitar ' + x.nombre + ' de esta versión?','Quitar').then(ok=>{if(ok)this.ejecutar(this.costeo.retirarTela(this.id,x.id),'Tela eliminada.');}); }
  agregarInsumo(): void { if (!this.editable || !this.nuevoInsumoId || !this.nuevoInsumoCantidad || this.nuevoInsumoCantidad<=0) { this.mensaje='Selecciona un insumo e indica una cantidad mayor que cero.'; return; } this.ejecutar(this.costeo.agregarInsumo(this.id,{insumoId:Number(this.nuevoInsumoId),cantidad:this.nuevoInsumoCantidad,precioUnitarioAplicado:this.nuevoInsumoPrecio || undefined,observacion:this.nuevoInsumoObservacion.trim()||undefined}),'Insumo agregado.',()=>{this.nuevoInsumoId='';this.nuevoInsumoCantidad=null;this.nuevoInsumoPrecio=null;this.nuevoInsumoObservacion='';}); }
  abrirEdicionInsumo(x: VersionCosteoInsumo): void { this.editandoInsumo=x; this.editCantidad=Number(x.cantidad); this.editPrecio=Number(x.precio_unitario_aplicado); this.editObservacion=x.observacion??''; }
  guardarInsumo(): void { if(this.editandoInsumo&&this.editCantidad&&this.editCantidad>0)this.ejecutar(this.costeo.actualizarInsumo(this.id,this.editandoInsumo.id,{cantidad:this.editCantidad,precioUnitarioAplicado:this.editPrecio || undefined,observacion:this.editObservacion.trim()||undefined}),'Insumo actualizado.',()=>this.editandoInsumo=undefined); }
  eliminarInsumo(x: VersionCosteoInsumo): void { void this.dialogos.solicitar('Quitar insumo','¿Deseas quitar ' + x.nombre + ' de esta versión?','Quitar').then(ok=>{if(ok)this.ejecutar(this.costeo.retirarInsumo(this.id,x.id),'Insumo eliminado.');}); }
  agregarOperacion(): void { if (!this.editable || !this.nuevaOperacion.trim() || !this.nuevaMaquinariaId || !this.nuevoTiempoSegundos || this.nuevoTiempoSegundos<=0 || this.nuevaCosturaCm===null || this.nuevaCosturaCm<0) { this.mensaje='Completa operación, maquinaria, tiempo y costura válidos.'; return; } this.ejecutar(this.costeo.agregarDetalleOrden(this.id,{operacion:this.nuevaOperacion.trim(),descripcion:this.nuevaDescripcionOperacion.trim()||undefined,maquinariaId:Number(this.nuevaMaquinariaId),tiempoSegundos:this.nuevoTiempoSegundos,costuraCm:this.nuevaCosturaCm}),'Fila operacional agregada.',()=>{this.nuevaOperacion='';this.nuevaDescripcionOperacion='';this.nuevaMaquinariaId='';this.nuevoTiempoSegundos=null;this.nuevaCosturaCm=null;}); }
  editarOperacion(x: OrdenOperacionalDetalle): void { this.editandoOperacion={...x}; }
  guardarOperacion(): void { const x=this.editandoOperacion; if(!x)return; this.ejecutar(this.costeo.actualizarDetalleOrden(this.id,x.id,{operacion:x.operacion,descripcion:x.descripcion||undefined,maquinariaId:Number(x.maquinariaId),tiempoSegundos:Number(x.tiempoSegundos),costuraCm:Number(x.costuraCm)}),'Fila operacional actualizada.',()=>this.editandoOperacion=undefined); }
  eliminarOperacion(x: OrdenOperacionalDetalle): void { void this.dialogos.solicitar('Eliminar operación','La fila se retirará de la orden operacional.','Eliminar').then(ok=>{if(ok)this.ejecutar(this.costeo.retirarDetalleOrden(this.id,x.id),'Fila operacional eliminada.');}); }
  confirmar(): void { if (!this.version) return; if (this.modal==='finalizar') this.ejecutar(this.costeo.finalizar(this.id),'Versión finalizada.',()=>this.modal=null); if(this.modal==='cancelar')this.ejecutar(this.costeo.cancelar(this.id),'Versión cancelada.',()=>this.modal=null); if(this.modal==='nueva')this.costeo.nuevaVersion(this.id).subscribe({next:v=>void this.router.navigate(['/versiones-costeo',v.id]),error:e=>{this.modal=null;this.mensaje=this.error(e);}}); }
  private ejecutar(operacion: Observable<unknown>, exito: string, despues?: () => void): void { this.cargando=true; operacion.subscribe({next:()=>{despues?.();this.mensaje=exito;this.refrescar();},error:e=>{this.cargando=false;this.mensaje=this.error(e);}}); }
  private porcentajeValido(valor:number):boolean{return Number.isFinite(Number(valor))&&Number(valor)>=0&&Number(valor)<=100;}
  private error(error:{error?:{message?:string|string[]}}):string{const mensaje=error.error?.message;return Array.isArray(mensaje)?mensaje.join(' '):mensaje??'No fue posible completar la operación.';}
}