import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { forkJoin, Observable } from 'rxjs';
import { AuthService } from '../../../core/services/auth.service';
import { CatalogosService, Insumo, Tela } from '../../../core/services/catalogos.service';
import { ProduccionService } from '../../../core/services/produccion.service';
import { CosteoService, DetalleVersionCosteo, MedidaConfiguracion, VersionCosteoInsumo, VersionCosteoMedida, VersionCosteoTela } from '../../../core/services/costeo.service';

type FilaMedida = MedidaConfiguracion & { valor: number | null };
type ModalAccion = 'finalizar' | 'cancelar' | 'nueva' | null;
@Component({ selector: 'app-costeo-detail', standalone: true, imports: [CommonModule, FormsModule, RouterLink], templateUrl: './costeo-detail.component.html', styleUrl: './costeo-detail.component.scss' })
export class CosteoDetailComponent implements OnInit {
  private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private readonly costeo = inject(CosteoService); private readonly produccion = inject(ProduccionService); private readonly catalogos = inject(CatalogosService); private readonly auth = inject(AuthService);
  id = ''; version?: DetalleVersionCosteo; medidas: FilaMedida[] = []; telas: VersionCosteoTela[] = []; insumos: VersionCosteoInsumo[] = []; catalogoTelas: Tela[] = []; catalogoInsumos: Insumo[] = [];
  mensaje = ''; cargando = false; ordenProduccionId?: string; sinOrdenProduccion = false; modal: ModalAccion = null; nombre = ''; descripcion = ''; manoObra = 0; ganancia = 0;
  nuevaTelaId = ''; nuevaTelaCantidad: number | null = null; nuevaTelaObservacion = ''; nuevoInsumoId = ''; nuevoInsumoCantidad: number | null = null; nuevoInsumoObservacion = '';
  editandoTela?: VersionCosteoTela; editandoInsumo?: VersionCosteoInsumo; editCantidad: number | null = null; editObservacion = '';
  get estudiante(): boolean { return this.auth.user?.rol === 'ESTUDIANTE'; }
  get editable(): boolean { return this.estudiante && this.version?.estado === 'BORRADOR'; }
  ngOnInit(): void { this.route.paramMap.subscribe(params => { this.id = params.get('id') ?? ''; this.cargarCatalogos(); this.refrescar(); }); }
  refrescar(): void { if (!this.id) return; this.cargando = true; forkJoin({ version: this.costeo.obtenerVersion(this.id), configuracion: this.costeo.configuracionMedidas(this.id), guardadas: this.costeo.obtenerMedidas(this.id), telas: this.costeo.obtenerTelas(this.id), insumos: this.costeo.obtenerInsumos(this.id) }).subscribe({ next: data => { this.version = data.version; this.nombre = data.version.nombre; this.descripcion = data.version.descripcion ?? ''; this.manoObra = Number(data.version.porcentajeManoObra); this.ganancia = Number(data.version.porcentajeGanancia); const valores = new Map(data.guardadas.map(medida => [String(medida.tipo_prenda_medida_id), Number(medida.valor)])); this.medidas = data.configuracion.map(configuracion => ({ ...configuracion, valor: valores.get(String(configuracion.tipo_prenda_medida_id)) ?? null })); this.telas = data.telas; this.insumos = data.insumos; this.verificarProduccion(data.version); this.cargando = false; }, error: error => { this.cargando = false; this.mensaje = this.error(error); } }); }
  verificarProduccion(version: DetalleVersionCosteo): void { if (version.estado !== 'FINALIZADA') return; this.produccion.ordenPorVersion(version.id).subscribe({ next: orden => { this.ordenProduccionId = orden.id; this.sinOrdenProduccion = false; }, error: () => { this.ordenProduccionId = undefined; this.sinOrdenProduccion = true; } }); }
  crearOrdenProduccion(): void { if (!this.version || !confirm('¿Crear la orden de producción para esta versión finalizada?')) return; this.cargando = true; this.produccion.crearOrden(this.version.id).subscribe({ next: orden => void this.router.navigate(['/produccion', orden.id]), error: error => { this.cargando = false; this.mensaje = this.error(error); } }); }
  verProduccion(): void { if (this.ordenProduccionId) void this.router.navigate(['/produccion', this.ordenProduccionId]); }  cargarCatalogos(): void { this.catalogos.listar<Tela>('telas', { estado: 'ACTIVO' }).subscribe({ next: telas => this.catalogoTelas = telas }); this.catalogos.listar<Insumo>('insumos', { estado: 'ACTIVO' }).subscribe({ next: insumos => this.catalogoInsumos = insumos }); }
  guardarCabecera(): void { if (!this.editable || !this.nombre.trim()) return; this.ejecutar(this.costeo.actualizarVersion(this.id, { nombre: this.nombre.trim(), descripcion: this.descripcion.trim() || undefined }), 'Cabecera actualizada.'); }
  guardarPorcentajes(): void { if (!this.editable || !this.porcentajeValido(this.manoObra) || !this.porcentajeValido(this.ganancia)) { this.mensaje = 'Los porcentajes deben estar entre 0 y 100.'; return; } this.ejecutar(this.costeo.actualizarVersion(this.id, { porcentajeManoObra: this.manoObra, porcentajeGanancia: this.ganancia }), 'Porcentajes actualizados.'); }
  guardarMedidas(): void { if (!this.editable) return; const medidas = this.medidas.filter(medida => medida.valor !== null && Number(medida.valor) > 0).map(medida => ({ tipoPrendaMedidaId: Number(medida.tipo_prenda_medida_id), valor: Number(medida.valor) })); if (!medidas.length) { this.mensaje = 'Registra al menos una medida válida.'; return; } this.ejecutar(this.costeo.guardarMedidas(this.id, { medidas }), 'Medidas guardadas.'); }
  agregarTela(): void { if (!this.editable || !this.nuevaTelaId || !this.nuevaTelaCantidad || this.nuevaTelaCantidad <= 0) { this.mensaje = 'Selecciona una tela e indica una cantidad mayor que cero.'; return; } this.ejecutar(this.costeo.agregarTela(this.id, { telaId: Number(this.nuevaTelaId), cantidadMetros: Number(this.nuevaTelaCantidad), cantidadMetrosSugerida: null, reglaConsumoTelaId: null, observacion: this.nuevaTelaObservacion.trim() || undefined }), 'Tela agregada.', () => { this.nuevaTelaId = ''; this.nuevaTelaCantidad = null; this.nuevaTelaObservacion = ''; }); }
  abrirEdicionTela(tela: VersionCosteoTela): void { this.editandoTela = tela; this.editCantidad = Number(tela.cantidad_metros); this.editObservacion = tela.observacion ?? ''; }
  guardarTela(): void { if (!this.editandoTela || !this.editCantidad || this.editCantidad <= 0) return; this.ejecutar(this.costeo.actualizarTela(this.id, this.editandoTela.id, { cantidadMetros: this.editCantidad, observacion: this.editObservacion.trim() || undefined }), 'Tela actualizada.', () => this.editandoTela = undefined); }
  eliminarTela(tela: VersionCosteoTela): void { if (confirm(`¿Quitar ${tela.nombre} de esta versión?`)) this.ejecutar(this.costeo.retirarTela(this.id, tela.id), 'Tela eliminada.'); }
  agregarInsumo(): void { if (!this.editable || !this.nuevoInsumoId || !this.nuevoInsumoCantidad || this.nuevoInsumoCantidad <= 0) { this.mensaje = 'Selecciona un insumo e indica una cantidad mayor que cero.'; return; } this.ejecutar(this.costeo.agregarInsumo(this.id, { insumoId: Number(this.nuevoInsumoId), cantidad: Number(this.nuevoInsumoCantidad), observacion: this.nuevoInsumoObservacion.trim() || undefined }), 'Insumo agregado.', () => { this.nuevoInsumoId = ''; this.nuevoInsumoCantidad = null; this.nuevoInsumoObservacion = ''; }); }
  abrirEdicionInsumo(insumo: VersionCosteoInsumo): void { this.editandoInsumo = insumo; this.editCantidad = Number(insumo.cantidad); this.editObservacion = insumo.observacion ?? ''; }
  guardarInsumo(): void { if (!this.editandoInsumo || !this.editCantidad || this.editCantidad <= 0) return; this.ejecutar(this.costeo.actualizarInsumo(this.id, this.editandoInsumo.id, { cantidad: this.editCantidad, observacion: this.editObservacion.trim() || undefined }), 'Insumo actualizado.', () => this.editandoInsumo = undefined); }
  eliminarInsumo(insumo: VersionCosteoInsumo): void { if (confirm(`¿Quitar ${insumo.nombre} de esta versión?`)) this.ejecutar(this.costeo.retirarInsumo(this.id, insumo.id), 'Insumo eliminado.'); }
  confirmar(): void { if (!this.version) return; if (this.modal === 'finalizar') this.ejecutar(this.costeo.finalizar(this.id), 'Versión finalizada.', () => this.modal = null); if (this.modal === 'cancelar') this.ejecutar(this.costeo.cancelar(this.id), 'Versión cancelada.', () => this.modal = null); if (this.modal === 'nueva') this.costeo.nuevaVersion(this.id).subscribe({ next: version => location.assign(`/versiones-costeo/${version.id}`), error: error => { this.modal = null; this.mensaje = this.error(error); } }); }
  private ejecutar(operacion: Observable<unknown>, exito: string, despues?: () => void): void { this.cargando = true; operacion.subscribe({ next: () => { despues?.(); this.mensaje = exito; this.refrescar(); }, error: (error: unknown) => { this.cargando = false; this.mensaje = this.error(error as { error?: { message?: string | string[] } }); } }); }
  private porcentajeValido(valor: number): boolean { return Number.isFinite(Number(valor)) && Number(valor) >= 0 && Number(valor) <= 100; }
  private error(error: { error?: { message?: string | string[] } }): string { const mensaje = error.error?.message; return Array.isArray(mensaje) ? mensaje.join(' ') : mensaje ?? 'No fue posible completar la operación.'; }
}

