import { Component, OnDestroy, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common'; import { FormsModule } from '@angular/forms'; import { ActivatedRoute, Router, RouterLink } from '@angular/router'; import { forkJoin } from 'rxjs';
import { AuthService } from '../../core/services/auth.service'; import { Proyecto, ProyectosService } from '../../core/services/proyectos.service'; import { CosteoService, VersionCosteo, VersionCosteoInsumo, VersionCosteoMedida, VersionCosteoTela } from '../../core/services/costeo.service'; import { FichaDiseno, FichaDisenoService, GuardarFichaDiseno, PaletaColor, TipoImagenFicha } from './ficha-diseno.service';
type ImagenesUrl = Partial<Record<TipoImagenFicha, string>>; interface FichaForm { nombreColeccion:string;referencia:string;temporada:string;marca:string;linea:string;categoria:string;target:string;estilo:string;silueta:string;tallas:string;uso:string;fundamentacion:string;detallesConstructivos:string;acabados:string;tejidoReferencial:string; }
const CAMPOS:Array<{key:keyof FichaForm;label:string}>=[{key:'nombreColeccion',label:'Nombre de colección'},{key:'referencia',label:'Referencia'},{key:'temporada',label:'Temporada'},{key:'marca',label:'Marca'},{key:'linea',label:'Línea'},{key:'categoria',label:'Categoría'},{key:'target',label:'Target'},{key:'estilo',label:'Estilo'},{key:'silueta',label:'Silueta'},{key:'tallas',label:'Tallas'},{key:'uso',label:'Uso'}];
const TIPOS:Array<{tipo:TipoImagenFicha;titulo:string;principal:boolean}>=[{tipo:'delantera',titulo:'Vista delantera',principal:true},{tipo:'espalda',titulo:'Vista posterior',principal:true},{tipo:'detalle',titulo:'Detalle',principal:false},{tipo:'tejido',titulo:'Tejido referencial',principal:false}];
@Component({selector:'app-ficha-diseno',standalone:true,imports:[CommonModule,FormsModule,RouterLink],templateUrl:'./ficha-diseno.component.html',styleUrl:'./ficha-diseno.component.scss'})
export class FichaDisenoComponent implements OnInit,OnDestroy{
 private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly auth=inject(AuthService);private readonly proyectos=inject(ProyectosService);private readonly fichaService=inject(FichaDisenoService);private readonly costeo=inject(CosteoService);
 readonly campos=CAMPOS;readonly tipos=TIPOS;proyectoId='';proyecto?:Proyecto;proyectosDisponibles:Proyecto[]=[];ficha?:FichaDiseno;urls:ImagenesUrl={};paleta:PaletaColor[]=[];versiones:VersionCosteo[]=[];medidas:VersionCosteoMedida[]=[];telas:VersionCosteoTela[]=[];insumos:VersionCosteoInsumo[]=[];mensaje='';error='';cargando=false;guardando=false;form:FichaForm=this.formVacio();
 get editable():boolean{return this.auth.user?.rol==='ESTUDIANTE'} get seleccionando():boolean{return !this.proyectoId} get tieneVersionFinalizada():boolean{return this.versiones.some(version=>version.estado==='FINALIZADA')}
 ngOnInit():void{this.route.paramMap.subscribe(x=>{this.proyectoId=x.get('proyectoId')??'';this.limpiarUrls();this.proyectoId?this.cargar():this.cargarProyectos()})}ngOnDestroy():void{this.limpiarUrls()}
 cargarProyectos():void{this.cargando=true;this.proyectos.list().subscribe({next:x=>{this.proyectosDisponibles=x;this.cargando=false},error:()=>{this.error='No fue posible cargar los proyectos.';this.cargando=false}})}
 cargar():void{this.cargando=true;this.error='';forkJoin({proyecto:this.proyectos.one(this.proyectoId),ficha:this.fichaService.obtener(this.proyectoId)}).subscribe({next:x=>{this.proyecto=x.proyecto;this.aplicarFicha(x.ficha.ficha);this.cargarCosteo();this.cargando=false},error:e=>{this.cargando=false;if(e.status===403){this.error='No tienes permisos para consultar esta ficha.';setTimeout(()=>void this.router.navigate(['/proyectos']),1200)}else this.error='No fue posible cargar la ficha de diseño.'}})}
 private aplicarFicha(f:FichaDiseno|null):void{this.ficha=f??undefined;this.form=this.formVacio();this.paleta=f?.paletaColores?.map(x=>({...x}))??[];if(f){for(const c of CAMPOS)this.form[c.key]=(f as unknown as Partial<FichaForm>)[c.key]??'';this.form.fundamentacion=f.fundamentacion??'';this.form.detallesConstructivos=f.detallesConstructivos??'';this.form.acabados=f.acabados??'';this.form.tejidoReferencial=f.tejidoReferencial??'';for(const i of TIPOS)if(f.imagenes[i.tipo])this.fichaService.obtenerImagen(this.proyectoId,i.tipo).subscribe({next:b=>this.urls[i.tipo]=URL.createObjectURL(b)})}}
 private cargarCosteo():void{this.costeo.listarVersiones(this.proyectoId).subscribe({next:v=>{this.versiones=v;const fin=v.find(x=>x.estado==='FINALIZADA');if(fin)forkJoin({medidas:this.costeo.obtenerMedidas(fin.id),telas:this.costeo.obtenerTelas(fin.id),insumos:this.costeo.obtenerInsumos(fin.id)}).subscribe({next:x=>{this.medidas=x.medidas;this.telas=x.telas;this.insumos=x.insumos}})}})}
 guardar():void{if(!this.editable||this.guardando)return;if(this.paleta.some(x=>!x.nombre.trim()||!/^#[0-9A-F]{6}$/i.test(x.hex))){this.error='Cada color debe tener nombre y código HEX válido.';return}this.guardando=true;const data:GuardarFichaDiseno={...this.form,paletaColores:this.paleta.map(x=>({nombre:x.nombre.trim(),hex:x.hex.toUpperCase()}))};this.fichaService.guardar(this.proyectoId,data).subscribe({next:x=>{this.ficha=x;this.mensaje='Ficha guardada correctamente.';this.guardando=false},error:e=>{this.guardando=false;this.error=e.error?.message??'No fue posible guardar la ficha.'}})}
 agregarColor():void{this.paleta.push({nombre:'',hex:'#1C4E80'})}eliminarColor(i:number):void{this.paleta.splice(i,1)}
 seleccionarArchivo(e:Event,t:TipoImagenFicha):void{const a=(e.target as HTMLInputElement).files?.[0];if(!a)return;if(!['image/jpeg','image/png','image/webp'].includes(a.type)||a.size>5242880){this.error='Selecciona una imagen JPG, PNG o WEBP de máximo 5 MB.';return}if(this.ficha?.imagenes[t]&&!confirm('¿Deseas reemplazar esta imagen?'))return;this.fichaService.subirImagen(this.proyectoId,t,a).subscribe({next:f=>{this.ficha=f;if(this.urls[t])URL.revokeObjectURL(this.urls[t]!);this.urls[t]=URL.createObjectURL(a);this.mensaje='Imagen actualizada correctamente.'},error:x=>this.error=x.error?.message??'No fue posible cargar la imagen.'})}
 eliminarImagen(t:TipoImagenFicha):void{if(!confirm('¿Eliminar esta imagen de la ficha?'))return;this.fichaService.eliminarImagen(this.proyectoId,t).subscribe({next:f=>{this.ficha=f;if(this.urls[t])URL.revokeObjectURL(this.urls[t]!);delete this.urls[t];this.mensaje='Imagen eliminada.'},error:x=>this.error=x.error?.message??'No fue posible eliminar la imagen.'})}
 private limpiarUrls():void{Object.values(this.urls).forEach(x=>URL.revokeObjectURL(x));this.urls={}}private formVacio():FichaForm{return{nombreColeccion:'',referencia:'',temporada:'',marca:'',linea:'',categoria:'',target:'',estilo:'',silueta:'',tallas:'',uso:'',fundamentacion:'',detallesConstructivos:'',acabados:'',tejidoReferencial:''}}
}