import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AdministracionService, Role, User } from '../../core/services/administracion.service';

type ModalMode = '' | 'create' | 'edit' | 'state' | 'password';
@Component({
  selector:'app-usuarios', standalone:true, imports:[CommonModule,ReactiveFormsModule],
  template:`<section class="page"><header class="page-head"><div><p>Administración</p><h1>Gestión de usuarios</h1><span>Administra los usuarios y accesos de MANAGIX.</span></div><button class="primary" type="button" (click)="abrirCrear()">+ Nuevo usuario</button></header>
  <div class="filters"><input aria-label="Buscar usuario" placeholder="Buscar usuario" [value]="search" (input)="search=$any($event.target).value;load()"><select aria-label="Filtrar por rol" (change)="rol=$any($event.target).value;load()"><option value="">Todos los roles</option><option *ngFor="let r of roles" [value]="r.id">{{r.nombre}}</option></select><select aria-label="Filtrar por estado" (change)="estado=$any($event.target).value;load()"><option value="">Todos los estados</option><option>ACTIVO</option><option>INACTIVO</option><option>BLOQUEADO</option></select></div>
  <p class="feedback" *ngIf="message" [class.error]="isError">{{message}}</p>
  <div class="table-wrap"><div class="table"><div class="row head"><b>Usuario</b><b>Correo</b><b>Rol</b><b>Estado</b><b>Acciones</b></div><div class="row" *ngFor="let u of users"><span data-label="Usuario">{{u.nombre}} {{u.apellido}}</span><span data-label="Correo">{{u.correo}}</span><span data-label="Rol">{{u.rol}}</span><span data-label="Estado" class="badge" [class.off]="u.estado!=='ACTIVO'">{{u.estado}}</span><span class="actions" data-label="Acciones"><button type="button" class="action-trigger" (click)="toggleActions(u.id)" [attr.aria-expanded]="openActions===u.id">Acciones <span>⋮</span></button><div class="action-menu" *ngIf="openActions===u.id"><button type="button" (click)="abrirEditar(u)">Editar usuario</button><button type="button" (click)="abrirEstado(u)">Cambiar estado</button><button type="button" (click)="abrirClave(u)">Cambiar contraseña</button></div></span></div></div></div>
  <div class="modal" *ngIf="mode" (click)="cerrar()"><form class="dialog" [formGroup]="form" (ngSubmit)="guardar()" (click)="$event.stopPropagation()" *ngIf="mode==='create'||mode==='edit'"><header><h2>{{mode==='create'?'Nuevo usuario':'Editar usuario'}}</h2><button type="button" class="close" (click)="cerrar()" aria-label="Cerrar">×</button></header><label>Nombre<input formControlName="nombre" autocomplete="given-name"></label><label>Apellido<input formControlName="apellido" autocomplete="family-name"></label><label *ngIf="mode==='create'">Correo electrónico<input formControlName="correo" autocomplete="email"></label><label>Rol<select formControlName="rolId"><option value="">Seleccione un rol</option><option *ngFor="let r of roles" [value]="r.id">{{r.nombre}}</option></select></label><ng-container *ngIf="mode==='create'"><label>Contraseña<input type="password" formControlName="password" autocomplete="new-password"></label><label>Confirmar contraseña<input type="password" formControlName="confirmPassword" autocomplete="new-password"></label></ng-container><p class="feedback error" *ngIf="modalMessage">{{modalMessage}}</p><footer><button type="button" class="secondary" (click)="cerrar()">Cancelar</button><button class="primary" [disabled]="loading">{{loading?'Guardando…':'Guardar usuario'}}</button></footer></form>
  <form class="dialog" [formGroup]="stateForm" (ngSubmit)="guardarEstado()" (click)="$event.stopPropagation()" *ngIf="mode==='state'&&selected"><header><h2>Cambiar estado del usuario</h2><button type="button" class="close" (click)="cerrar()" aria-label="Cerrar">×</button></header><p><strong>Usuario:</strong> {{selected.nombre}} {{selected.apellido}}</p><p><strong>Estado actual:</strong> <span class="badge">{{selected.estado}}</span></p><label>Nuevo estado<select formControlName="estado"><option value="ACTIVO">ACTIVO</option><option value="INACTIVO">INACTIVO</option><option value="BLOQUEADO">BLOQUEADO</option></select></label><p class="feedback error" *ngIf="modalMessage">{{modalMessage}}</p><footer><button type="button" class="secondary" (click)="cerrar()">Cancelar</button><button class="primary" [disabled]="loading">{{loading?'Guardando…':'Guardar cambio'}}</button></footer></form>
  <form class="dialog" [formGroup]="passwordForm" (ngSubmit)="guardarClave()" (click)="$event.stopPropagation()" *ngIf="mode==='password'&&selected"><header><h2>Cambiar contraseña</h2><button type="button" class="close" (click)="cerrar()" aria-label="Cerrar">×</button></header><p>Define una contraseña nueva para <strong>{{selected.nombre}} {{selected.apellido}}</strong>.</p><label>Nueva contraseña<input type="password" formControlName="password" autocomplete="new-password"></label><label>Confirmar contraseña<input type="password" formControlName="confirmPassword" autocomplete="new-password"></label><p class="feedback error" *ngIf="modalMessage">{{modalMessage}}</p><footer><button type="button" class="secondary" (click)="cerrar()">Cancelar</button><button class="primary" [disabled]="loading">{{loading?'Guardando…':'Restablecer contraseña'}}</button></footer></form></div></section>`,
  styles:[`.page{max-width:1240px}.page-head{display:flex;justify-content:space-between;gap:16px;align-items:start}.page h1{margin:4px 0;color:var(--color-azul)}.page-head p{margin:0;color:var(--color-naranja);font-weight:700}.primary,.secondary,.action-trigger,.action-menu button,.close{border:0;border-radius:8px;padding:9px 12px;cursor:pointer}.primary{background:var(--color-naranja);color:#fff}.secondary{background:#e7edf5;color:#334155}.filters{display:flex;flex-wrap:wrap;gap:10px;margin:24px 0}.filters input,.filters select,.dialog input,.dialog select{box-sizing:border-box;width:100%;padding:10px;border:1px solid var(--color-border);border-radius:8px;background:#fff}.filters>*{flex:1 1 190px}.table-wrap{border:1px solid var(--color-border);border-radius:12px;background:#fff;overflow-x:auto}.table{min-width:760px}.row{display:grid;grid-template-columns:1.15fr 1.4fr 1fr 1fr 1.45fr;gap:12px;align-items:center;padding:13px 15px;border-bottom:1px solid var(--color-border)}.head{background:#f8fafc}.badge{color:#167543;font-weight:700}.badge.off{color:#b45309}.actions{position:relative;display:flex;justify-content:flex-start}.action-trigger{display:inline-flex;gap:8px;align-items:center;background:#eef4fb;color:var(--color-azul);font-weight:700}.action-trigger span{font-size:17px}.action-menu{position:absolute;z-index:5;top:calc(100% + 5px);right:0;min-width:200px;padding:6px;border:1px solid var(--color-border);border-radius:10px;background:#fff;box-shadow:0 12px 30px #17324d24}.action-menu button{display:block;width:100%;background:transparent;color:#24364b;text-align:left}.action-menu button:hover{background:#f3f7fc}.feedback{margin:12px 0;color:#167543}.feedback.error{color:#b91c1c}.modal{position:fixed;z-index:100;inset:0;display:grid;place-items:center;padding:16px;background:#0f1f3680}.dialog{display:grid;gap:14px;width:min(100%,460px);max-height:calc(100dvh - 32px);overflow-y:auto;padding:24px;border-radius:14px;background:#fff;box-shadow:0 20px 60px #0004}.dialog header,.dialog footer{display:flex;justify-content:space-between;gap:10px;align-items:center}.dialog h2{margin:0;color:var(--color-azul)}.dialog label{display:grid;gap:7px;color:#334155;font-weight:600}.close{padding:2px 8px;background:transparent;color:#64748b;font-size:28px;line-height:1}.dialog footer{justify-content:flex-end;margin-top:4px}@media(max-width:650px){.page-head{flex-direction:column}.page-head .primary{width:100%}.table{min-width:0}.head{display:none}.row{grid-template-columns:1fr;padding:15px}.row>span{display:grid;grid-template-columns:112px minmax(0,1fr);gap:8px}.row>span::before{content:attr(data-label);font-weight:700;color:#64748b}.actions{align-items:start}.action-menu{left:112px;right:auto;top:30px}.dialog{padding:20px}.dialog footer{flex-direction:column-reverse}.dialog footer button{width:100%}}`]
})
export class UsuariosComponent implements OnInit {
  private readonly service=inject(AdministracionService); private readonly fb=inject(FormBuilder);
  users:User[]=[]; roles:Role[]=[]; search=''; rol=''; estado=''; mode:ModalMode=''; selected?:User; openActions=''; loading=false; message=''; modalMessage=''; isError=false;
  form=this.fb.nonNullable.group({nombre:['',Validators.required],apellido:['',Validators.required],correo:['',[Validators.required,Validators.email]],rolId:['',Validators.required],password:['',[Validators.minLength(8)]],confirmPassword:['']});
  stateForm=this.fb.nonNullable.group({estado:['ACTIVO' as 'ACTIVO'|'INACTIVO'|'BLOQUEADO',Validators.required]});
  passwordForm=this.fb.nonNullable.group({password:['',[Validators.required,Validators.minLength(8)]],confirmPassword:['',Validators.required]});
  ngOnInit(){this.service.roles().subscribe(x=>this.roles=x);this.load();}
  load(){this.service.users({search:this.search,rolId:this.rol,estado:this.estado}).subscribe({next:x=>this.users=x.data,error:e=>this.notice(e.error?.message??'No fue posible cargar los usuarios.',true)});}
  toggleActions(id:string){this.openActions=this.openActions===id?'':id;}
  abrirCrear(){this.mode='create';this.selected=undefined;this.modalMessage='';this.form.reset({nombre:'',apellido:'',correo:'',rolId:'',password:'',confirmPassword:''});}
  abrirEditar(user:User){this.openActions='';this.mode='edit';this.selected=user;this.modalMessage='';this.form.reset({nombre:user.nombre,apellido:user.apellido,correo:user.correo,rolId:user.rolId,password:'',confirmPassword:''});}
  abrirEstado(user:User){this.openActions='';this.mode='state';this.selected=user;this.modalMessage='';this.stateForm.reset({estado:user.estado as 'ACTIVO'|'INACTIVO'|'BLOQUEADO'});}
  abrirClave(user:User){this.openActions='';this.mode='password';this.selected=user;this.modalMessage='';this.passwordForm.reset({password:'',confirmPassword:''});}
  cerrar(){this.mode='';this.selected=undefined;this.modalMessage='';}
  guardar(){if(this.form.invalid){this.modalMessage='Completa los campos obligatorios correctamente.';return;}const value=this.form.getRawValue();if(this.mode==='create'&&value.password!==value.confirmPassword){this.modalMessage='Las contraseñas no coinciden.';return;}this.loading=true;const request=this.mode==='create'?this.service.create({nombre:value.nombre,apellido:value.apellido,correo:value.correo,rolId:value.rolId,password:value.password}):this.service.update(this.selected!.id,{nombre:value.nombre,apellido:value.apellido,rolId:value.rolId});request.subscribe({next:()=>{this.loading=false;this.cerrar();this.notice('Cambios guardados correctamente.');this.load();},error:e=>{this.loading=false;this.modalMessage=e.error?.message??'No fue posible guardar el usuario.';}});}
  guardarEstado(){if(this.stateForm.invalid||!this.selected)return;this.loading=true;this.service.state(this.selected.id,this.stateForm.getRawValue().estado).subscribe({next:()=>{this.loading=false;this.cerrar();this.notice('Estado actualizado correctamente.');this.load();},error:e=>{this.loading=false;this.modalMessage=e.error?.message??'No fue posible cambiar el estado.';}});}
  guardarClave(){if(this.passwordForm.invalid||!this.selected)return;const value=this.passwordForm.getRawValue();if(value.password!==value.confirmPassword){this.modalMessage='Las contraseñas no coinciden.';return;}this.loading=true;this.service.password(this.selected.id,value.password).subscribe({next:()=>{this.loading=false;this.cerrar();this.notice('Contraseña restablecida correctamente.');},error:e=>{this.loading=false;this.modalMessage=e.error?.message??'No fue posible restablecer la contraseña.';}});}
  private notice(message:string,error=false){this.message=message;this.isError=error;}
}