import { Body, Controller, Get, Param, ParseIntPipe, Patch, Post, Query, Request, UseGuards } from '@nestjs/common';
import { CatalogosService } from './catalogos.service'; import { JwtAuthGuard } from '../auth/jwt-auth.guard'; import { RolesGuard } from '../auth/roles.guard'; import { Roles } from '../auth/roles.decorator';
import { CreateTipoPrendaDto, UpdateTipoPrendaDto, CreateMedidaDto, UpdateMedidaDto, CreateTelaDto, UpdateTelaDto, CreateInsumoDto, UpdateInsumoDto, CreateTpmDto, UpdateTpmDto, CreateReglaDto, UpdateReglaDto, EstadoDto } from './dto/catalogos.dto';
type AuthRequest={user:{sub:string}}; type Filters=Record<string,string>;
@UseGuards(JwtAuthGuard,RolesGuard) @Controller() export class CatalogosController { constructor(private readonly service:CatalogosService) {}
@Get('tipos-prenda') tipos(@Query()q:Filters){return this.service.list('tipos-prenda',q)} @Get('tipos-prenda/:id') tipo(@Param('id',ParseIntPipe)id:number){return this.service.one('tipos-prenda',String(id))} @Roles('ADMINISTRADOR') @Post('tipos-prenda') crearTipo(@Body()d:CreateTipoPrendaDto,@Request()r:AuthRequest){return this.service.save('tipos-prenda',d,r.user.sub)} @Roles('ADMINISTRADOR') @Patch('tipos-prenda/:id') editarTipo(@Param('id',ParseIntPipe)id:number,@Body()d:UpdateTipoPrendaDto,@Request()r:AuthRequest){return this.service.save('tipos-prenda',d,r.user.sub,String(id))} @Roles('ADMINISTRADOR') @Patch('tipos-prenda/:id/estado') estadoTipo(@Param('id',ParseIntPipe)id:number,@Body()d:EstadoDto,@Request()r:AuthRequest){return this.service.estado('tipos-prenda',String(id),d.estado,r.user.sub)}
@Get('medidas') medidas(@Query()q:Filters){return this.service.list('medidas',q)} @Get('medidas/:id') medida(@Param('id',ParseIntPipe)id:number){return this.service.one('medidas',String(id))} @Roles('ADMINISTRADOR') @Post('medidas') crearMedida(@Body()d:CreateMedidaDto,@Request()r:AuthRequest){return this.service.save('medidas',d,r.user.sub)} @Roles('ADMINISTRADOR') @Patch('medidas/:id') editarMedida(@Param('id',ParseIntPipe)id:number,@Body()d:UpdateMedidaDto,@Request()r:AuthRequest){return this.service.save('medidas',d,r.user.sub,String(id))} @Roles('ADMINISTRADOR') @Patch('medidas/:id/estado') estadoMedida(@Param('id',ParseIntPipe)id:number,@Body()d:EstadoDto,@Request()r:AuthRequest){return this.service.estado('medidas',String(id),d.estado,r.user.sub)}
@Get('tipos-prenda/:id/medidas') medidasTipo(@Param('id',ParseIntPipe)id:number){return this.service.medidas(String(id))} @Roles('ADMINISTRADOR') @Post('tipos-prenda/:id/medidas') asociar(@Param('id',ParseIntPipe)id:number,@Body()d:CreateTpmDto,@Request()r:AuthRequest){return this.service.addMedida(String(id),d,r.user.sub)} @Roles('ADMINISTRADOR') @Patch('tipos-prenda/:tipoPrendaId/medidas/:relacionId') editarRelacion(@Param('tipoPrendaId',ParseIntPipe)t:number,@Param('relacionId',ParseIntPipe)id:number,@Body()d:UpdateTpmDto,@Request()r:AuthRequest){return this.service.updMedida(String(t),String(id),d,r.user.sub)} @Roles('ADMINISTRADOR') @Patch('tipos-prenda/:tipoPrendaId/medidas/:relacionId/estado') estadoRelacion(@Param('tipoPrendaId',ParseIntPipe)t:number,@Param('relacionId',ParseIntPipe)id:number,@Body()d:EstadoDto,@Request()r:AuthRequest){return this.service.updMedida(String(t),String(id),d,r.user.sub)}
@Get('telas') telas(@Query()q:Filters){return this.service.list('telas',q)} @Get('telas/:id') tela(@Param('id',ParseIntPipe)id:number){return this.service.one('telas',String(id))} @Roles('ADMINISTRADOR') @Post('telas') crearTela(@Body()d:CreateTelaDto,@Request()r:AuthRequest){return this.service.save('telas',d,r.user.sub)} @Roles('ADMINISTRADOR') @Patch('telas/:id') editarTela(@Param('id',ParseIntPipe)id:number,@Body()d:UpdateTelaDto,@Request()r:AuthRequest){return this.service.save('telas',d,r.user.sub,String(id))} @Roles('ADMINISTRADOR') @Patch('telas/:id/estado') estadoTela(@Param('id',ParseIntPipe)id:number,@Body()d:EstadoDto,@Request()r:AuthRequest){return this.service.estado('telas',String(id),d.estado,r.user.sub)}
@Get('insumos') insumos(@Query()q:Filters){return this.service.list('insumos',q)} @Get('insumos/:id') insumo(@Param('id',ParseIntPipe)id:number){return this.service.one('insumos',String(id))} @Roles('ADMINISTRADOR') @Post('insumos') crearInsumo(@Body()d:CreateInsumoDto,@Request()r:AuthRequest){return this.service.save('insumos',d,r.user.sub)} @Roles('ADMINISTRADOR') @Patch('insumos/:id') editarInsumo(@Param('id',ParseIntPipe)id:number,@Body()d:UpdateInsumoDto,@Request()r:AuthRequest){return this.service.save('insumos',d,r.user.sub,String(id))} @Roles('ADMINISTRADOR') @Patch('insumos/:id/estado') estadoInsumo(@Param('id',ParseIntPipe)id:number,@Body()d:EstadoDto,@Request()r:AuthRequest){return this.service.estado('insumos',String(id),d.estado,r.user.sub)}
@Get('reglas-consumo-tela') reglas(@Query()q:Filters){return this.service.list('reglas-consumo-tela',q)} @Get('reglas-consumo-tela/:id') regla(@Param('id',ParseIntPipe)id:number){return this.service.one('reglas-consumo-tela',String(id))} @Roles('ADMINISTRADOR') @Post('reglas-consumo-tela') crearRegla(@Body()d:CreateReglaDto,@Request()r:AuthRequest){return this.service.save('reglas-consumo-tela',d,r.user.sub)} @Roles('ADMINISTRADOR') @Patch('reglas-consumo-tela/:id') editarRegla(@Param('id',ParseIntPipe)id:number,@Body()d:UpdateReglaDto,@Request()r:AuthRequest){return this.service.save('reglas-consumo-tela',d,r.user.sub,String(id))} @Roles('ADMINISTRADOR') @Patch('reglas-consumo-tela/:id/estado') estadoRegla(@Param('id',ParseIntPipe)id:number,@Body()d:EstadoDto,@Request()r:AuthRequest){return this.service.estado('reglas-consumo-tela',String(id),d.estado,r.user.sub)} }

