import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { EntityManager, ILike, Repository } from 'typeorm';
import { Publicacion, EstadoPublicacion } from './entities/publicacion.entity';
import { Auditoria, AccionAuditoria } from '../administracion/entities/auditoria.entity';
import { Usuario, EstadoUsuario } from '../auth/entities/usuario.entity';
import { Notificacion, TipoNotificacion } from '../notificaciones/entities/notificacion.entity';
import { join } from 'path';
import { promises as fs, createReadStream } from 'fs';
import { CreatePublicacionDto, UpdatePublicacionDto } from './dto/publicacion.dto';
type UsuarioAuth={sub:string;rol:string};
@Injectable()
export class PortalAcademicoService { constructor(@InjectRepository(Publicacion) private readonly publicaciones:Repository<Publicacion>,@InjectRepository(Auditoria) private readonly auditorias:Repository<Auditoria>,@InjectRepository(Usuario) private readonly usuarios:Repository<Usuario>,@InjectRepository(Notificacion) private readonly notificaciones:Repository<Notificacion>){}
 async list(usuario:UsuarioAuth,estado?:EstadoPublicacion,search?:string){ const where:any={}; if(usuario.rol==='ESTUDIANTE')where.estado=EstadoPublicacion.PUBLICADA; else if(usuario.rol==='DOCENTE'&&estado&&estado!==EstadoPublicacion.PUBLICADA){where.estado=estado;where.creadoPorUsuarioId=usuario.sub;} else if(estado)where.estado=estado; if(search?.trim())where.titulo=ILike(`%${search.trim()}%`); const data=await this.publicaciones.find({where,relations:{creador:true,publicador:true},order:{fechaPublicacion:'DESC',createdAt:'DESC'}}); return data.map(x=>this.respuesta(x)); }
 async one(id:string,usuario:UsuarioAuth){const p=await this.publicaciones.findOne({where:{id},relations:{creador:true,publicador:true}});if(!p)throw new NotFoundException('Publicación no encontrada.');this.ver(p,usuario);return this.respuesta(p);}
 async create(dto:CreatePublicacionDto,u:UsuarioAuth){this.escribir(u);return this.transaccion(async m=>{const r=m.getRepository(Publicacion);const id=await this.siguiente(r);const p=await r.save(r.create({id,titulo:dto.titulo.trim(),contenido:dto.contenido.trim(),imagenStorageKey:dto.imagenStorageKey?.trim()||null,estado:EstadoPublicacion.BORRADOR,creadoPorUsuarioId:u.sub,publicadoPorUsuarioId:null,fechaPublicacion:null}));await this.auditar(m,u.sub,p.id,'Publicación creada como borrador.',AccionAuditoria.CREAR);return this.respuesta(p);});}
 async update(id:string,dto:UpdatePublicacionDto,u:UsuarioAuth){return this.transaccion(async m=>{const p=await this.buscar(m,id);this.editar(p,u);if(dto.titulo!==undefined)p.titulo=dto.titulo.trim();if(dto.contenido!==undefined)p.contenido=dto.contenido.trim();if(dto.imagenStorageKey!==undefined)p.imagenStorageKey=dto.imagenStorageKey?.trim()||null;const guardada=await m.getRepository(Publicacion).save(p);await this.auditar(m,u.sub,id,'Contenido de publicación actualizado.');return this.respuesta(guardada);});}
 async publicar(id:string,u:UsuarioAuth){return this.cambiarEstado(id,u,EstadoPublicacion.PUBLICADA,'Publicación publicada.');} async ocultar(id:string,u:UsuarioAuth){return this.cambiarEstado(id,u,EstadoPublicacion.OCULTA,'Publicación ocultada.');} async archivar(id:string,u:UsuarioAuth){return this.cambiarEstado(id,u,EstadoPublicacion.ARCHIVADA,'Publicación archivada.');}
 private async cambiarEstado(id:string,u:UsuarioAuth,estado:EstadoPublicacion,descripcion:string){return this.transaccion(async m=>{const p=await this.buscar(m,id);this.editar(p,u);if(p.estado===estado)throw new BadRequestException('La publicación ya tiene ese estado.');p.estado=estado;if(estado===EstadoPublicacion.PUBLICADA){p.publicadoPorUsuarioId=u.sub;p.fechaPublicacion=new Date();}const guardada=await m.getRepository(Publicacion).save(p);if(estado===EstadoPublicacion.PUBLICADA)await this.notificarPublicacion(m,guardada,u.sub);await this.auditar(m,u.sub,id,descripcion);return this.respuesta(guardada);});}
 async subirImagen(id:string,archivo:{originalname:string;mimetype:string;size:number;buffer:Buffer}|undefined,u:UsuarioAuth){if(!archivo)throw new BadRequestException('Debe adjuntar una imagen.');if(!['image/jpeg','image/png','image/webp'].includes(archivo.mimetype)||archivo.size>5*1024*1024)throw new BadRequestException('La imagen debe ser JPG, PNG o WEBP y no superar 5 MB.');const p=await this.publicaciones.findOne({where:{id}});if(!p)throw new NotFoundException('Publicación no encontrada.');this.editar(p,u);const ext=archivo.mimetype==='image/png'?'png':archivo.mimetype==='image/webp'?'webp':'jpg';const key=`${id}/${Date.now()}.${ext}`;const dir=join(process.cwd(),'uploads','portal-academico','publicaciones',id);await fs.mkdir(dir,{recursive:true});await fs.writeFile(join(dir,key.split('/').pop()!),archivo.buffer);if(p.imagenStorageKey)await fs.rm(join(process.cwd(),'uploads','portal-academico','publicaciones',p.imagenStorageKey),{force:true});p.imagenStorageKey=key;await this.publicaciones.save(p);await this.transaccion(m=>this.auditar(m,u.sub,id,'Imagen de publicación actualizada.').then(()=>Promise.resolve()));return this.respuesta(p);}
 async imagen(id:string,u:UsuarioAuth){const p=await this.publicaciones.findOne({where:{id}});if(!p)throw new NotFoundException('Publicación no encontrada.');this.ver(p,u);if(!p.imagenStorageKey)throw new NotFoundException('La publicación no tiene imagen.');const path=join(process.cwd(),'uploads','portal-academico','publicaciones',p.imagenStorageKey);try{await fs.access(path);}catch{throw new NotFoundException('Imagen no disponible.');}return {path,mime:p.imagenStorageKey.endsWith('.png')?'image/png':p.imagenStorageKey.endsWith('.webp')?'image/webp':'image/jpeg'};}
 async eliminarImagen(id:string,u:UsuarioAuth){const p=await this.publicaciones.findOne({where:{id}});if(!p)throw new NotFoundException('Publicación no encontrada.');this.editar(p,u);if(p.imagenStorageKey){await fs.rm(join(process.cwd(),'uploads','portal-academico','publicaciones',p.imagenStorageKey),{force:true});p.imagenStorageKey=null;await this.publicaciones.save(p);await this.transaccion(m=>this.auditar(m,u.sub,id,'Imagen de publicación eliminada.').then(()=>Promise.resolve()));}return this.respuesta(p);}
 private async notificarPublicacion(m:EntityManager,p:Publicacion,autor:string){const usuarios=await m.getRepository(Usuario).createQueryBuilder('u').leftJoinAndSelect('u.rol','r').where("u.estado='ACTIVO'").andWhere("r.nombre IN ('ESTUDIANTE','DOCENTE')").andWhere('u.id<>:autor',{autor}).getMany();const repo=m.getRepository(Notificacion);let next=(await repo.createQueryBuilder().select('COALESCE(MAX(id),0)+1','id').getRawOne<{id:string}>())?.id??'1';for(const destinatario of usuarios){await repo.save(repo.create({id:next,usuarioId:destinatario.id,titulo:'Nueva publicación académica',mensaje:p.titulo,tipo:TipoNotificacion.PUBLICACION,referenciaTipo:'PUBLICACION',referenciaId:p.id,leida:false,fechaLectura:null}));next=String(BigInt(next)+1n);}} private ver(p:Publicacion,u:UsuarioAuth){if(u.rol==='ADMINISTRADOR')return;if(u.rol==='ESTUDIANTE'&&p.estado===EstadoPublicacion.PUBLICADA)return;if(u.rol==='DOCENTE'&&(p.estado===EstadoPublicacion.PUBLICADA||p.creadoPorUsuarioId===u.sub))return;throw new ForbiddenException('No tiene acceso a esta publicación.');} private escribir(u:UsuarioAuth){if(!['DOCENTE','ADMINISTRADOR'].includes(u.rol))throw new ForbiddenException('No tiene permisos para administrar publicaciones.');} private editar(p:Publicacion,u:UsuarioAuth){this.escribir(u);if(u.rol==='DOCENTE'&&p.creadoPorUsuarioId!==u.sub)throw new ForbiddenException('Solo puede modificar publicaciones propias.');}
 private respuesta(p:Publicacion){return{id:p.id,titulo:p.titulo,contenido:p.contenido,tieneImagen:!!p.imagenStorageKey,estado:p.estado,autor:p.creador?{id:p.creador.id,nombre:p.creador.nombre,apellido:p.creador.apellido}:undefined,fecha_publicacion:p.fechaPublicacion,created_at:p.createdAt,updated_at:p.updatedAt};} private async buscar(m:EntityManager,id:string){const p=await m.getRepository(Publicacion).findOne({where:{id},relations:{creador:true,publicador:true}});if(!p)throw new NotFoundException('Publicación no encontrada.');return p;} private async siguiente(r:Repository<Publicacion>){const raw=await r.createQueryBuilder().select('COALESCE(MAX(id),0)+1','id').getRawOne<{id:string}>();return raw?.id??'0';} private async auditar(m:EntityManager,usuarioId:string,entidadId:string,descripcion:string,accion:AccionAuditoria=AccionAuditoria.ACTUALIZAR){const r=m.getRepository(Auditoria);const id=await this.siguiente(r as unknown as Repository<Publicacion>);await r.save(r.create({id,usuarioId,modulo:'PORTAL_ACADEMICO',accion,entidad:'publicacion',entidadId,descripcion,metadatos:null,direccionIp:null,userAgent:null}));} private transaccion<T>(fn:(m:EntityManager)=>Promise<T>):Promise<T>{return this.publicaciones.manager.transaction(fn);} }
