import { Body, Controller, Delete, Get, HttpCode, HttpStatus, Param, ParseIntPipe, Patch, Post, Query, Request, StreamableFile, UploadedFile, UseGuards, UseInterceptors } from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { createReadStream } from 'fs';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PortalAcademicoService } from './portal-academico.service';
import { CreatePublicacionDto, UpdatePublicacionDto } from './dto/publicacion.dto';
import { EstadoPublicacion } from './entities/publicacion.entity';
type AuthRequest={user:{sub:string;rol:string}};
@UseGuards(JwtAuthGuard) @Controller('publicaciones')
export class PortalAcademicoController { constructor(private readonly service:PortalAcademicoService){} @Get() list(@Request()r:AuthRequest,@Query('estado')estado?:EstadoPublicacion,@Query('search')search?:string){return this.service.list(r.user,estado,search)} @Get(':id') one(@Param('id',ParseIntPipe)id:number,@Request()r:AuthRequest){return this.service.one(String(id),r.user)} @Post() create(@Body()d:CreatePublicacionDto,@Request()r:AuthRequest){return this.service.create(d,r.user)} @Patch(':id') update(@Param('id',ParseIntPipe)id:number,@Body()d:UpdatePublicacionDto,@Request()r:AuthRequest){return this.service.update(String(id),d,r.user)} @Post(':id/imagen') @UseInterceptors(FileInterceptor('file',{limits:{fileSize:6*1024*1024}})) imagen(@Param('id',ParseIntPipe)id:number,@UploadedFile()file:{originalname:string;mimetype:string;size:number;buffer:Buffer}|undefined,@Request()r:AuthRequest){return this.service.subirImagen(String(id),file,r.user)} @Get(':id/imagen') async obtenerImagen(@Param('id',ParseIntPipe)id:number,@Request()r:AuthRequest){const imagen=await this.service.imagen(String(id),r.user);return new StreamableFile(createReadStream(imagen.path),{type:imagen.mime});} @Delete(':id/imagen') eliminarImagen(@Param('id',ParseIntPipe)id:number,@Request()r:AuthRequest){return this.service.eliminarImagen(String(id),r.user)} @Post(':id/publicar') @HttpCode(HttpStatus.OK) publicar(@Param('id',ParseIntPipe)id:number,@Request()r:AuthRequest){return this.service.publicar(String(id),r.user)} @Post(':id/ocultar') @HttpCode(HttpStatus.OK) ocultar(@Param('id',ParseIntPipe)id:number,@Request()r:AuthRequest){return this.service.ocultar(String(id),r.user)} @Post(':id/archivar') @HttpCode(HttpStatus.OK) archivar(@Param('id',ParseIntPipe)id:number,@Request()r:AuthRequest){return this.service.archivar(String(id),r.user)} }
