import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'; import { InjectRepository } from '@nestjs/typeorm'; import { Repository } from 'typeorm'; import { Auditoria,AccionAuditoria } from '../administracion/entities/auditoria.entity'; import { Proyecto } from '../proyectos/entities/proyecto.entity'; import { EstadoVersionCosteo,VersionCosteo } from '../costeo/entities/version-costeo.entity'; import { CreateLineaSamDto,CreateOperacionSamDto,EstadoSamDto,UpdateLineaSamDto,UpdateOperacionSamDto } from './dto/sam.dto'; import { EstadoOperacionSam,OperacionSam,VersionCosteoOperacionSam } from './entities/sam.entities';
type U={sub:string;rol:string};
@Injectable() export class SamService { constructor(@InjectRepository(OperacionSam)private ops:Repository<OperacionSam>,@InjectRepository(VersionCosteoOperacionSam)private lines:Repository<VersionCosteoOperacionSam>,@InjectRepository(VersionCosteo)private versions:Repository<VersionCosteo>,@InjectRepository(Proyecto)private projects:Repository<Proyecto>,@InjectRepository(Auditoria)private auditRepo:Repository<Auditoria>) {}
 private async audit(u:string,a:AccionAuditoria,id:string,d:string,e:string){const n=await this.auditRepo.createQueryBuilder('a').select('coalesce(max(a.id),0)+1','id').getRawOne<{id:string}>();await this.auditRepo.save(this.auditRepo.create({id:n?.id??'1',usuarioId:u,modulo:'COSTEO',accion:a,entidad:e,entidadId:id,descripcion:d,metadatos:null,direccionIp:null,userAgent:null}))}
 async listar(q:{estado?:string;search?:string}){const b=this.ops.createQueryBuilder('o').orderBy('o.codigo','ASC');if(q.estado)b.andWhere('o.estado=:estado',q);if(q.search)b.andWhere('(o.codigo ILIKE :search OR o.nombre ILIKE :search)',{search:'%'+q.search+'%'});return b.getMany()}
 async una(id:string){const x=await this.ops.findOneBy({id});if(!x)throw new NotFoundException('Operación SAM no encontrada.');return x}
 async crear(d:CreateOperacionSamDto,u:U){try{const n=await this.ops.createQueryBuilder('o').select('coalesce(max(o.id),0)+1','id').getRawOne<{id:string}>();const x=await this.ops.save(this.ops.create({id:n?.id??'1',...d,codigo:d.codigo.trim().toUpperCase(),nombre:d.nombre.trim(),descripcion:d.descripcion?.trim()??null,samReferencial:String(d.samReferencial),estado:EstadoOperacionSam.ACTIVO}));await this.audit(u.sub,AccionAuditoria.CREAR,x.id,'Operación SAM creada.','operacion_sam');return x}catch(e){if((e as {code?:string}).code==='23505')throw new ConflictException('Código o nombre SAM ya existe.');throw e}}
 async actualizar(id:string,d:UpdateOperacionSamDto,u:U){const x=await this.una(id);try{Object.assign(x,{...d,codigo:d.codigo?.trim().toUpperCase(),nombre:d.nombre?.trim(),descripcion:d.descripcion?.trim(),samReferencial:d.samReferencial===undefined?undefined:String(d.samReferencial)});const r=await this.ops.save(x);await this.audit(u.sub,AccionAuditoria.ACTUALIZAR,id,'Operación SAM actualizada.','operacion_sam');return r}catch(e){if((e as {code?:string}).code==='23505')throw new ConflictException('Código o nombre SAM ya existe.');throw e}}
 async estado(id:string,d:EstadoSamDto,u:U){const x=await this.una(id);x.estado=d.estado as EstadoOperacionSam;const r=await this.ops.save(x);await this.audit(u.sub,d.estado==='INACTIVO'?AccionAuditoria.DESACTIVAR:AccionAuditoria.ACTUALIZAR,id,'Estado de operación SAM actualizado.','operacion_sam');return r}
 private async version(id:string,u:U,write=false){const v=await this.versions.findOneBy({id});if(!v)throw new NotFoundException('Versión no encontrada.');const p=await this.projects.findOneBy({id:v.proyectoId});if(u.rol==='ESTUDIANTE'&&p?.estudianteId!==u.sub)throw new ForbiddenException('No tiene acceso a esta versión.');if(write&&u.rol!=='ESTUDIANTE')throw new ForbiddenException('Solo el estudiante propietario puede editar.');if(write&&v.estado!==EstadoVersionCosteo.BORRADOR)throw new BadRequestException('Solo versiones BORRADOR son editables.');return v}
 async listarLineas(id:string,u:U){await this.version(id,u);const xs=await this.lines.find({where:{versionCosteoId:id},order:{id:'ASC'}});const ops=await this.ops.findByIds(xs.map(x=>x.operacionSamId));const map=new Map(ops.map(x=>[x.id,x]));const operaciones=xs.map(x=>({id:x.id,operacionSamId:x.operacionSamId,codigo:map.get(x.operacionSamId)?.codigo,nombre:map.get(x.operacionSamId)?.nombre,descripcion:map.get(x.operacionSamId)?.descripcion,samAplicado:Number(x.samAplicado),cantidad:Number(x.cantidad),subtotalMinutos:Number(x.subtotalMinutos),observacion:x.observacion,createdAt:x.createdAt,updatedAt:x.updatedAt}));return{operaciones,samTotal:operaciones.reduce((s,x)=>s+x.subtotalMinutos,0)}}
 async agregar(id:string,d:CreateLineaSamDto,u:U){await this.version(id,u,true);const op=await this.una(String(d.operacionSamId));if(op.estado!==EstadoOperacionSam.ACTIVO)throw new BadRequestException('La operación SAM está inactiva.');if(await this.lines.findOneBy({versionCosteoId:id,operacionSamId:op.id}))throw new ConflictException('La operación ya fue agregada a esta versión.');const n=await this.lines.createQueryBuilder('l').select('coalesce(max(l.id),0)+1','id').getRawOne<{id:string}>();const sam=Number(op.samReferencial),sub=Number((sam*d.cantidad).toFixed(2));const x=await this.lines.save(this.lines.create({id:n?.id??'1',versionCosteoId:id,operacionSamId:op.id,samAplicado:String(sam),cantidad:String(d.cantidad),subtotalMinutos:String(sub),observacion:d.observacion?.trim()??null}));await this.audit(u.sub,AccionAuditoria.CREAR,x.id,'Operación SAM agregada a versión.','version_costeo_operacion_sam');return x}
 async actualizarLinea(id:string,l:string,d:UpdateLineaSamDto,u:U){await this.version(id,u,true);const x=await this.lines.findOneBy({id:l,versionCosteoId:id});if(!x)throw new NotFoundException('Línea SAM no encontrada.');if(d.cantidad!==undefined){x.cantidad=String(d.cantidad);x.subtotalMinutos=String(Number((Number(x.samAplicado)*d.cantidad).toFixed(2)))}if(d.observacion!==undefined)x.observacion=d.observacion.trim()||null;const r=await this.lines.save(x);await this.audit(u.sub,AccionAuditoria.ACTUALIZAR,l,'Operación SAM actualizada.','version_costeo_operacion_sam');return r}
 async retirar(id:string,l:string,u:U){await this.version(id,u,true);const x=await this.lines.findOneBy({id:l,versionCosteoId:id});if(!x)throw new NotFoundException('Línea SAM no encontrada.');await this.lines.remove(x);await this.audit(u.sub,AccionAuditoria.ACTUALIZAR,l,'Operación SAM retirada de versión.','version_costeo_operacion_sam');return{ok:true}}
}