import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common'; import { InjectRepository } from '@nestjs/typeorm'; import * as bcrypt from 'bcrypt'; import { ILike, Repository } from 'typeorm'; import { Usuario, EstadoUsuario } from '../auth/entities/usuario.entity'; import { Rol, EstadoCatalogo } from '../auth/entities/rol.entity'; import { Auditoria, AccionAuditoria } from './entities/auditoria.entity'; import { ConfiguracionGeneral } from './entities/configuracion-general.entity'; import { CreateUsuarioDto, UpdateEstadoDto, UpdateUsuarioDto, ResetPasswordDto } from './dto/usuario.dto'; import { UpdateConfiguracionDto } from './dto/configuracion.dto'; import { QueryAuditoriaDto } from './dto/auditoria.dto';
const safe=(u:Usuario)=>({id:u.id,nombre:u.nombre,apellido:u.apellido,correo:u.correo,estado:u.estado,rol:u.rol?u.rol.nombre:undefined,rolId:u.rolId,createdAt:u.createdAt,updatedAt:u.updatedAt});
@Injectable() export class AdministracionService { constructor(@InjectRepository(Usuario) private users:Repository<Usuario>,@InjectRepository(Rol) private roles:Repository<Rol>,@InjectRepository(Auditoria) private audit:Repository<Auditoria>,@InjectRepository(ConfiguracionGeneral) private config:Repository<ConfiguracionGeneral>){}
 async log(usuarioId:string,accion:AccionAuditoria,entidad:string,entidadId:string,descripcion:string){await this.audit.save(this.audit.create({id:(await this.audit.createQueryBuilder().select('COALESCE(MAX(id),0)+1','id').getRawOne()).id,usuarioId,modulo:'ADMINISTRACION',accion,entidad,entidadId,descripcion,metadatos:null,direccionIp:null,userAgent:null}))}
 async list(query:{search?:string;rolId?:string;estado?:EstadoUsuario;page?:number;limit?:number}){const page=Math.max(1,Number(query.page)||1),limit=Math.min(100,Math.max(1,Number(query.limit)||20));const qb=this.users.createQueryBuilder('u').leftJoinAndSelect('u.rol','r'); if(query.search){qb.andWhere('(u.nombre ILIKE :s OR u.apellido ILIKE :s OR u.correo ILIKE :s)',{s:`%${query.search}%`})} if(query.rolId)qb.andWhere('u.rol_id=:rolId',{rolId:query.rolId});if(query.estado)qb.andWhere('u.estado=:estado',{estado:query.estado}); const [data,total]=await qb.orderBy('u.id','ASC').skip((page-1)*limit).take(limit).getManyAndCount();return {data:data.map(safe),total,page,limit}}
 async one(id:string){const u=await this.users.findOne({where:{id},relations:{rol:true}});if(!u)throw new NotFoundException('Usuario no encontrado.');return safe(u)}
 async create(dto:CreateUsuarioDto,admin:string){if(await this.users.findOne({where:{correo:dto.correo}}))throw new ConflictException('El correo ya est� registrado.');const r=await this.roles.findOne({where:{id:dto.rolId,estado:EstadoCatalogo.ACTIVO}});if(!r)throw new BadRequestException('Rol inv�lido o inactivo.');const id=(await this.users.createQueryBuilder().select('COALESCE(MAX(id),0)+1','id').getRawOne()).id;const u=this.users.create({id,rolId:r.id,nombre:dto.nombre,apellido:dto.apellido,correo:dto.correo,passwordHash:await bcrypt.hash(dto.password,12),estado:dto.estado??EstadoUsuario.ACTIVO});await this.users.save(u);const created=await this.users.findOneOrFail({where:{id},relations:{rol:true}});await this.log(admin,AccionAuditoria.CREAR,'usuario',id,'Usuario creado.');return safe(created)}
 async update(id:string,dto:UpdateUsuarioDto,admin:string){const u=await this.users.findOne({where:{id},relations:{rol:true}});if(!u)throw new NotFoundException('Usuario no encontrado.');Object.assign(u,dto);if(dto.rolId){const r=await this.roles.findOne({where:{id:dto.rolId,estado:EstadoCatalogo.ACTIVO}});if(!r)throw new BadRequestException('Rol inv�lido o inactivo.');u.rolId=r.id;u.rol=r}await this.users.save(u);const result=await this.one(id);await this.log(admin,AccionAuditoria.ACTUALIZAR,'usuario',id,'Usuario actualizado.');return result}
 async estado(id:string,dto:UpdateEstadoDto,admin:string){const u=await this.users.findOneBy({id});if(!u)throw new NotFoundException('Usuario no encontrado.');u.estado=dto.estado;await this.users.save(u);await this.log(admin,dto.estado===EstadoUsuario.ACTIVO?AccionAuditoria.ACTUALIZAR:AccionAuditoria.DESACTIVAR,'usuario',id,'Estado actualizado.');return this.one(id)}
 async reset(id:string,dto:ResetPasswordDto,admin:string){const u=await this.users.findOneBy({id});if(!u)throw new NotFoundException('Usuario no encontrado.');u.passwordHash=await bcrypt.hash(dto.password,12);await this.users.save(u);await this.log(admin,AccionAuditoria.ACTUALIZAR,'usuario',id,'Contrase�a restablecida.');return {message:'Contrase�a actualizada.'}}
 async activeRoles(){return this.roles.find({where:{estado:EstadoCatalogo.ACTIVO},select:{id:true,nombre:true,descripcion:true,estado:true}})}
 async listAuditoria(query:QueryAuditoriaDto){const page=query.page??1,limit=query.limit??20;const qb=this.auditQuery();this.applyAuditFilters(qb,query);const total=await qb.getCount();const rows=await qb.orderBy('a.created_at','DESC').addOrderBy('a.id','DESC').offset((page-1)*limit).limit(limit).getRawMany();return{data:rows.map(row=>this.auditPublicRow(row)),total,page,limit}}
 async oneAuditoria(id:string){const row=await this.auditQuery().where('a.id=:id',{id}).getRawOne();if(!row)throw new NotFoundException('Registro de auditoría no encontrado.');return this.auditPublicRow(row)}
 private auditQuery(){return this.audit.createQueryBuilder('a').leftJoin(Usuario,'u','u.id=a.usuario_id').select('a.id','id').addSelect('a.usuario_id','usuarioId').addSelect('a.modulo','modulo').addSelect('a.accion','accion').addSelect('a.entidad','entidad').addSelect('a.entidad_id','entidadId').addSelect('a.descripcion','descripcion').addSelect('a.metadatos','metadata').addSelect('a.created_at','createdAt').addSelect('u.id','userId').addSelect('u.nombre','userNombre').addSelect('u.apellido','userApellido').addSelect('u.correo','userCorreo')}
 private applyAuditFilters(qb:ReturnType<Repository<Auditoria>['createQueryBuilder']>,query:QueryAuditoriaDto){if(query.modulo)qb.andWhere('a.modulo=:modulo',{modulo:query.modulo});if(query.accion)qb.andWhere('a.accion=:accion',{accion:query.accion});if(query.usuarioId)qb.andWhere('a.usuario_id=:usuarioId',{usuarioId:query.usuarioId});if(query.entidad)qb.andWhere('a.entidad=:entidad',{entidad:query.entidad});if(query.entidadId)qb.andWhere('a.entidad_id=:entidadId',{entidadId:query.entidadId});if(query.fechaDesde)qb.andWhere('a.created_at >= :fechaDesde',{fechaDesde:query.fechaDesde});if(query.fechaHasta)qb.andWhere('a.created_at <= :fechaHasta',{fechaHasta:`${query.fechaHasta}T23:59:59.999Z`});if(query.search){const search=`%${query.search.trim()}%`;qb.andWhere("(COALESCE(a.descripcion,'') ILIKE :search OR a.entidad ILIKE :search OR a.modulo ILIKE :search OR COALESCE(u.nombre,'') ILIKE :search OR COALESCE(u.apellido,'') ILIKE :search OR COALESCE(u.correo,'') ILIKE :search)",{search})}}
 private auditPublicRow(row:Record<string,unknown>){const userId=row.userId?String(row.userId):null;return{id:String(row.id),usuario:userId?{id:userId,nombre:[row.userNombre,row.userApellido].filter(Boolean).join(' ')||'Usuario no disponible',correo:row.userCorreo?String(row.userCorreo):null}:null,modulo:String(row.modulo),accion:row.accion,entidad:String(row.entidad),entidadId:row.entidadId?String(row.entidadId):null,descripcion:row.descripcion?String(row.descripcion):null,metadata:this.sanitizeMetadata(row.metadata),createdAt:row.createdAt}}
 private sanitizeMetadata(value:unknown):unknown{if(value===null||value===undefined||typeof value!=='object')return value;if(Array.isArray(value))return value.map(item=>this.sanitizeMetadata(item));const blocked=['password','password_hash','token','jwt','authorization','secret','refreshtoken','accesstoken','storage_key','storagekey','ruta','path'];return Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([key])=>!blocked.some(word=>key.toLowerCase().includes(word))).map(([key,item])=>[key,this.sanitizeMetadata(item)]))} async getConfig(admin:string){let c=await this.config.findOneBy({id:1});if(!c){await this.config.insert({id:1,nombreInstitucion:'Instituto Superior Yavirac',monedaCodigo:'USD',porcentajeManoObraDefecto:'0',porcentajeGananciaDefecto:'0',actualizadoPorUsuarioId:admin} as ConfiguracionGeneral);c=await this.config.findOneByOrFail({id:1})}return c}
 async patchConfig(dto:UpdateConfiguracionDto,admin:string){const c=await this.getConfig(admin);Object.assign(c,dto,{actualizadoPorUsuarioId:admin,monedaCodigo:'USD'});await this.config.save(c);await this.log(admin,AccionAuditoria.ACTUALIZAR,'configuracion_general','1','Configuraci�n actualizada.');return c}
}


