import { Component, OnDestroy, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { forkJoin } from 'rxjs';
import { environment } from '../../../../environments/environment';
import { EvidenciaEtapa, OrdenProduccion, OrdenProduccionEtapa, ProduccionService, RevisionEtapa } from '../../../core/services/produccion.service';
interface EvidenciaVista extends EvidenciaEtapa{preview?:string;}
@Component({selector:'app-revision-detail',standalone:true,imports:[CommonModule,FormsModule,RouterLink],templateUrl:'./revision-detail.component.html',styleUrl:'./revision-detail.component.scss'})
export class RevisionDetailComponent implements OnInit,OnDestroy{private readonly route=inject(ActivatedRoute);private readonly service=inject(ProduccionService);private readonly http=inject(HttpClient);ordenId='';etapaId='';orden?:OrdenProduccion;etapa?:OrdenProduccionEtapa;evidencias:EvidenciaVista[]=[];historial:RevisionEtapa[]=[];resultado:'OBSERVADA'|'APROBADA'='APROBADA';observacion='';modal=false;cargando=true;guardando=false;mensaje='';ngOnInit():void{this.route.paramMap.subscribe(p=>{this.ordenId=p.get('ordenId')??'';this.etapaId=p.get('etapaId')??'';this.cargar();});}ngOnDestroy():void{this.evidencias.forEach(e=>e.preview&&URL.revokeObjectURL(e.preview));}get revisable():boolean{return this.etapa?.estado==='COMPLETADA';}get ultima():RevisionEtapa|undefined{return this.historial[this.historial.length-1];}cargar():void{this.cargando=true;this.service.obtenerOrden(this.ordenId).subscribe({next:o=>{this.orden=o;forkJoin({etapas:this.service.etapas(this.ordenId),evidencias:this.service.evidencias(this.ordenId,this.etapaId),revisiones:this.service.revisiones(this.ordenId,this.etapaId)}).subscribe({next:d=>{this.etapa=d.etapas.find(e=>e.id===this.etapaId);this.historial=d.revisiones;this.evidencias=d.evidencias.map(e=>({...e}));this.evidencias.forEach(e=>this.preview(e));this.cargando=false;},error:e=>this.fallo(e)});},error:e=>this.fallo(e)});}registrar():void{if(this.resultado==='OBSERVADA'&&!this.observacion.trim()){this.mensaje='La observación es obligatoria cuando el resultado es OBSERVADA.';return;}this.guardando=true;this.service.crearRevision(this.ordenId,this.etapaId,{resultado:this.resultado,observacion:this.observacion.trim()||undefined}).subscribe({next:()=>{this.modal=false;this.observacion='';this.mensaje='Revisión registrada correctamente.';this.cargar();},error:e=>this.fallo(e)});}private preview(e:EvidenciaVista):void{this.http.get(`${environment.apiUrl}/evidencias/${e.id}/archivo`,{responseType:'blob'}).subscribe({next:b=>e.preview=URL.createObjectURL(b)});}private fallo(e:unknown):void{this.cargando=false;this.guardando=false;this.modal=false;const m=(e as {error?:{message?:string|string[]}}).error?.message;this.mensaje=Array.isArray(m)?m.join(' '):m??'No fue posible completar la operación.';}}
