import { Injectable } from '@nestjs/common';
import { existsSync } from 'fs';
import { resolve } from 'path';
import PDFDocument from 'pdfkit';

export type FichaIdentificacion={proyecto:string;descripcion?:string|null;estudiante:string;prenda:string;version:number;estado:string;fecha:Date;docente?:string|null;boceto?:string|null};
export type Fila=Record<string,string>;
export type EstiloSeccion='estandar'|'resumen'|'calculo-tiempo'|'financiero'|'evidencias';
export type SeccionPdf={titulo:string;columnas?:string[];filas?:Fila[];texto?:string;destacado?:Array<[string,string]>;imagenes?:Array<{titulo:string;path:string|null}>;estilo?:EstiloSeccion;total?:[string,string]};

/** Formatea exclusivamente la impresión del PDF; no altera los valores de cálculo. */
export function formatoNumeroPdf(valor:string|number|null|undefined,maxDecimales=4):string{const numero=Number(valor??0);return Number.isFinite(numero)?new Intl.NumberFormat('en-US',{minimumFractionDigits:0,maximumFractionDigits:maxDecimales,useGrouping:false}).format(numero):'0'}
export function formatoMonedaPdf(valor:string|number|null|undefined,maxDecimales=2):string{return `$${formatoNumeroPdf(valor,maxDecimales)}`}

@Injectable()
export class FichasManagixPdfService{
 private readonly logo=resolve(process.cwd(),'..','Frontend','src','assets','images','institution','yavirac-logo.png');private readonly left=42;private readonly width=511;private readonly bottom=48;
 async generar(titulo:string,identificacion:FichaIdentificacion,secciones:SeccionPdf[]):Promise<Buffer>{const doc=new PDFDocument({size:'A4',margin:this.left,compress:false,bufferPages:true,info:{Title:`${titulo} - MANAGIX`,Author:'MANAGIX'}});const chunks:Buffer[]=[];doc.on('data',(chunk:Buffer)=>chunks.push(chunk));const terminado=new Promise<Buffer>((resolve,reject)=>{doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject)});const originalAddPage=doc.addPage.bind(doc);doc.addPage=((options?:PDFKit.PDFDocumentOptions)=>{originalAddPage(options);this.encabezadoReducido(doc,titulo);return doc}) as typeof doc.addPage;this.encabezadoPrincipal(doc,titulo);this.identificacion(doc,identificacion);for(const seccion of secciones)this.seccion(doc,seccion);const pages=doc.bufferedPageRange();for(let index=pages.start;index<pages.start+pages.count;index+=1){doc.switchToPage(index);this.pie(doc,index-pages.start+1,pages.count,identificacion.fecha)}doc.end();return terminado}
 private encabezadoPrincipal(doc:PDFKit.PDFDocument,titulo:string):void{const top=34;if(existsSync(this.logo))doc.image(this.logo,this.left,top,{fit:[68,52],valign:'center'});doc.font('Helvetica-Bold').fontSize(9.4).fillColor('#17324d').text('INSTITUTO SUPERIOR TECNOLÓGICO',120,top+4,{width:345,align:'center'});doc.text('DE TURISMO Y PATRIMONIO YAVIRAC',120,top+18,{width:345,align:'center'});doc.font('Helvetica').fontSize(8).fillColor('#52677a').text('CARRERA DE DISEÑO DE MODAS',120,top+34,{width:345,align:'center'});doc.font('Helvetica-Bold').fontSize(11.5).fillColor('#0b4f82').text('MANAGIX',459,top+21,{width:94,align:'right'});doc.moveTo(this.left,96).lineTo(553,96).strokeColor('#cbd8e4').lineWidth(.7).stroke();doc.font('Helvetica-Bold').fontSize(16).fillColor('#0b4f82').text(titulo.toUpperCase(),this.left,115,{width:this.width,align:'center',characterSpacing:.2});doc.y=151}
 private identificacion(doc:PDFKit.PDFDocument,d:FichaIdentificacion):void{const y=doc.y,conBoceto=d.boceto!==undefined,alto=conBoceto?84:80;doc.roundedRect(this.left,y,this.width,alto,6).fillAndStroke('#f8fafc','#d7e3ec');this.columnaIdentificacion(doc,[['Proyecto',d.proyecto],['Tipo de prenda',d.prenda],['Estado',d.estado]],56,y+12,conBoceto?178:210);this.columnaIdentificacion(doc,[['Estudiante',d.estudiante],['Versión',`V${d.version}`],['Fecha de generación',this.fecha(d.fecha)]],conBoceto?250:307,y+12,conBoceto?178:210);if(conBoceto)this.boceto(doc,d.boceto??null,y+9);doc.y=y+alto+7;if(d.descripcion)this.parrafo(doc,d.descripcion)}
 private columnaIdentificacion(doc:PDFKit.PDFDocument,valores:Array<[string,string]>,x:number,y:number,width:number):void{valores.forEach(([etiqueta,valor],i)=>{const yy=y+i*21;doc.font('Helvetica-Bold').fontSize(6.8).fillColor('#64748b').text(etiqueta.toUpperCase(),x,yy,{width});doc.font('Helvetica').fontSize(8.4).fillColor('#17324d').text(valor||'No registrado',x,yy+8,{width,height:10,ellipsis:true})})}
 private boceto(doc:PDFKit.PDFDocument,path:string|null,y:number):void{const x=445;doc.roundedRect(x,y,91,65,4).fillAndStroke('#ffffff','#d7e3ec');if(path&&existsSync(path)){try{doc.image(path,x+5,y+5,{fit:[81,55],align:'center',valign:'center'});return}catch{/* etiqueta */}}doc.font('Helvetica').fontSize(6.5).fillColor('#64748b').text('Boceto no registrado',x+7,y+28,{width:77,align:'center'})}
 private encabezadoReducido(doc:PDFKit.PDFDocument,titulo:string):void{doc.font('Helvetica').fontSize(7.2).fillColor('#52677a').text(`Instituto Yavirac | Carrera de Diseño de Modas | ${titulo}`,this.left,26,{width:405});doc.font('Helvetica-Bold').fillColor('#0b4f82').text('MANAGIX',468,26,{width:84,align:'right'});doc.moveTo(this.left,38).lineTo(553,38).strokeColor('#d7e3ec').lineWidth(.55).stroke();doc.y=54}
 private pie(doc:PDFKit.PDFDocument,pagina:number,total:number,fecha:Date):void{const y=doc.page.height-27,bottom=doc.page.margins.bottom;doc.page.margins.bottom=0;doc.moveTo(this.left,y-6).lineTo(553,y-6).strokeColor('#d7e3ec').lineWidth(.5).stroke();doc.font('Helvetica').fontSize(6.8).fillColor('#64748b').text(`MANAGIX · ${this.fecha(fecha)}`,this.left,y,{width:260,lineBreak:false});doc.text(`Página ${pagina} de ${total}`,456,y,{width:97,align:'right',lineBreak:false});doc.page.margins.bottom=bottom}
 private seccion(doc:PDFKit.PDFDocument,seccion:SeccionPdf):void{const minimo=seccion.estilo==='financiero'?310:seccion.columnas?57:seccion.estilo==='calculo-tiempo'?120:46;this.espacio(doc,minimo);doc.moveDown(.55).font('Helvetica-Bold').fontSize(10.7).fillColor('#0b4f82').text(seccion.titulo.toUpperCase(),this.left);doc.moveTo(this.left,doc.y+3).lineTo(553,doc.y+3).strokeColor('#d97706').lineWidth(.65).stroke();doc.moveDown(.38);if(seccion.titulo.toLowerCase().includes('paleta')){this.paleta(doc,seccion.filas??[]);return}if(seccion.texto)this.parrafo(doc,seccion.texto);if(seccion.imagenes){if(seccion.estilo==='evidencias')this.evidencias(doc,seccion.imagenes);else this.galeria(doc,seccion.imagenes);}if(seccion.estilo==='calculo-tiempo')this.calculoTiempo(doc,seccion.destacado??[]);else if(seccion.estilo==='financiero')this.financiero(doc,seccion.destacado??[]);else if(seccion.estilo==='resumen')this.resumen(doc,seccion.destacado??[]);else if(seccion.destacado)this.detalles(doc,seccion.destacado,seccion.total);if(seccion.columnas){this.tabla(doc,seccion.columnas,seccion.filas??[]);if(seccion.total)this.filaDetalle(doc,seccion.total[0],seccion.total[1],true)}}
 private resumen(doc:PDFKit.PDFDocument,datos:Array<[string,string]>):void{for(let index=0;index<datos.length;index+=3){const fila=datos.slice(index,index+3);this.espacio(doc,53);const y=doc.y;fila.forEach(([etiqueta,valor],columna)=>{const x=this.left+columna*171;doc.roundedRect(x,y,163,46,4).fillAndStroke('#f8fafc','#d7e3ec');doc.font('Helvetica-Bold').fontSize(7).fillColor('#52677a').text(etiqueta.toUpperCase(),x+8,y+9,{width:147});doc.font('Helvetica-Bold').fontSize(10).fillColor('#17324d').text(valor,x+8,y+23,{width:147,align:'right',ellipsis:true})});doc.y=y+52}}
 private calculoTiempo(doc:PDFKit.PDFDocument,datos:Array<[string,string]>):void{const final=datos[datos.length-1],intermedios=datos.slice(0,-1);this.detalles(doc,intermedios);if(!final)return;this.espacio(doc,42);const y=doc.y;doc.roundedRect(this.left,y,this.width,34,5).fillAndStroke('#eaf3fb','#0b4f82');doc.font('Helvetica-Bold').fontSize(9.4).fillColor('#0b4f82').text(final[0].toUpperCase(),this.left+12,y+11,{width:300});doc.font('Helvetica-Bold').fontSize(12).fillColor('#0b4f82').text(final[1],370,y+9,{width:170,align:'right'});doc.y=y+42}
 private financiero(doc:PDFKit.PDFDocument,datos:Array<[string,string]>):void{const destacados=new Set(['COSTO DE PRENDA','SUBTOTAL','PVP']);datos.forEach(([etiqueta,valor])=>{const esDestacado=destacados.has(etiqueta.toUpperCase());this.espacio(doc,esDestacado?28:22);const y=doc.y;if(etiqueta.toUpperCase()==='PVP')doc.rect(this.left,y,this.width,26).fill('#0b4f82');else if(esDestacado)doc.rect(this.left,y,this.width,24).fill('#eaf3fb');else doc.moveTo(this.left,y+19).lineTo(553,y+19).strokeColor('#e5edf4').lineWidth(.45).stroke();const color=etiqueta.toUpperCase()==='PVP'?'#ffffff':'#17324d';doc.font(esDestacado?'Helvetica-Bold':'Helvetica').fontSize(esDestacado?8.8:8.2).fillColor(color).text(etiqueta,this.left+8,y+7,{width:330});doc.font('Helvetica-Bold').fontSize(esDestacado?10.8:8.7).fillColor(color).text(valor,378,y+(esDestacado?6:7),{width:158,align:'right'});doc.y=y+(esDestacado?29:23)})}
 private detalles(doc:PDFKit.PDFDocument,datos:Array<[string,string]>,total?:[string,string]):void{datos.forEach(([etiqueta,valor])=>this.filaDetalle(doc,etiqueta,valor));if(total)this.filaDetalle(doc,total[0],total[1],true)}
 private filaDetalle(doc:PDFKit.PDFDocument,etiqueta:string,valor:string,destacado=false):void{this.espacio(doc,destacado?25:20);const y=doc.y;if(destacado)doc.rect(this.left,y,this.width,22).fill('#eaf3fb');else doc.moveTo(this.left,y+18).lineTo(553,y+18).strokeColor('#e5edf4').lineWidth(.45).stroke();doc.font(destacado?'Helvetica-Bold':'Helvetica').fontSize(8.2).fillColor('#26364a').text(etiqueta,this.left+8,y+6,{width:320});doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#17324d').text(valor||'—',370,y+6,{width:166,align:'right',ellipsis:true});doc.y=y+(destacado?25:20)}
 private paleta(doc:PDFKit.PDFDocument,filas:Fila[]):void{if(!filas.length){this.parrafo(doc,'Sin colores registrados.');return}filas.forEach(fila=>{this.espacio(doc,24);const y=doc.y,hex=fila['Código']??fila.Codigo??'',valido=/^#[0-9a-fA-F]{6}$/.test(hex);doc.roundedRect(48,y+1,16,16,3).fillAndStroke(valido?hex:'#f8fafc','#94a3b8');doc.font('Helvetica').fontSize(8.6).fillColor('#26364a').text(`${fila.Color??'Color'} - ${hex||'Sin código'}`,74,y+4);doc.y=y+22})}
 private evidencias(doc:PDFKit.PDFDocument,imagenes:Array<{titulo:string;path:string|null}>):void{if(!imagenes.length){this.parrafo(doc,'Sin evidencias fotográficas registradas.');return}for(const imagen of imagenes){this.espacio(doc,292);const y=doc.y;doc.roundedRect(this.left,y,this.width,282,5).fillAndStroke('#f8fafc','#d7e3ec');doc.font('Helvetica-Bold').fontSize(8.2).fillColor('#17324d').text(imagen.titulo,this.left+10,y+10,{width:this.width-20});if(imagen.path&&existsSync(imagen.path)){try{doc.image(imagen.path,this.left+10,y+29,{fit:[this.width-20,242],align:'center',valign:'center'});doc.y=y+288;continue}catch{/* continúa con aviso seguro */}}doc.font('Helvetica').fontSize(8).fillColor('#64748b').text('La evidencia no pudo visualizarse.',this.left+10,y+143,{width:this.width-20,align:'center'});doc.y=y+288}}
 private galeria(doc:PDFKit.PDFDocument,imagenes:Array<{titulo:string;path:string|null}>):void{if(!imagenes.length){this.parrafo(doc,'Sin imágenes registradas.');return}for(let i=0;i<imagenes.length;i+=2){this.espacio(doc,132);const y=doc.y;imagenes.slice(i,i+2).forEach((imagen,indice)=>{const x=this.left+indice*260;doc.roundedRect(x,y,245,118,5).fillAndStroke('#f8fafc','#d7e3ec');doc.font('Helvetica-Bold').fontSize(7.2).fillColor('#52677a').text(imagen.titulo,x+7,y+7,{width:231,align:'center'});if(imagen.path&&existsSync(imagen.path)){try{doc.image(imagen.path,x+7,y+22,{fit:[231,88],align:'center',valign:'center'});return}catch{/* etiqueta */}}doc.font('Helvetica').fontSize(8).fillColor('#64748b').text('No registrada',x+7,y+60,{width:231,align:'center'})});doc.y=y+124}}
 private parrafo(doc:PDFKit.PDFDocument,texto:string):void{this.espacio(doc,Math.min(64,14+texto.length*.12));doc.font('Helvetica').fontSize(8.5).fillColor('#26364a').text(texto,{width:this.width,lineGap:2})}
 private tabla(doc:PDFKit.PDFDocument,columnas:string[],filas:Fila[]):void{const anchos=this.anchos(columnas),encabezado=()=>{const y=doc.y;doc.rect(this.left,y,this.width,22).fill('#0b4f82');let x=this.left;columnas.forEach((columna,index)=>{doc.font('Helvetica-Bold').fontSize(7.2).fillColor('#ffffff').text(columna,x+4,y+6,{width:anchos[index]-8,height:12,ellipsis:true,align:this.alineacion(columna,index)});x+=anchos[index]});doc.y=y+22},asegurarFila=(alto:number)=>{if(doc.y+alto>doc.page.height-this.bottom){doc.addPage();encabezado()}};encabezado();const datos=filas.length?filas:[Object.fromEntries([[columnas[0],'Sin registros disponibles']]) as Fila];datos.forEach((fila,filaIndice)=>{const valores=columnas.map(columna=>fila[columna]??'—'),alto=Math.max(22,...valores.map((valor,index)=>doc.font('Helvetica').fontSize(7.4).heightOfString(valor,{width:anchos[index]-8})+10));asegurarFila(alto);const y=doc.y;if(filaIndice%2===0)doc.rect(this.left,y,this.width,alto).fill('#f8fafc');doc.rect(this.left,y,this.width,alto).strokeColor('#d7e3ec').lineWidth(.35).stroke();let x=this.left;valores.forEach((valor,index)=>{doc.font('Helvetica').fontSize(7.4).fillColor('#26364a').text(valor,x+4,y+5,{width:anchos[index]-8,height:alto-8,ellipsis:true,align:this.alineacion(columnas[index],index)});x+=anchos[index]});doc.y=y+alto})}
 private anchos(columnas:string[]):number[]{if(columnas.length===6&&columnas[0]==='N.º')return[30,135,110,72,76,88];if(columnas.length===5&&columnas[0]==='Material')return[175,76,54,102,104];if(columnas.length===4)return[220,86,98,107];if(columnas.length===3)return[255,128,128];return columnas.map(()=>this.width/columnas.length)}
 private alineacion(columna:string,indice:number):'left'|'right'|'center'{if(indice===0&&['N.º','Orden'].includes(columna))return'center';return/valor|cantidad|precio|subtotal|costo|tiempo|costura|hilo|horas|metros|unidad/i.test(columna)?'right':'left'}
 private espacio(doc:PDFKit.PDFDocument,alto:number):void{if(doc.y+alto>doc.page.height-this.bottom)doc.addPage()}
 private fecha(fecha:Date):string{return new Intl.DateTimeFormat('en-US',{dateStyle:'medium'}).format(new Date(fecha))}
}